"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program.
	If not, see <https://www.gnu.org/licenses/>.
"""


"""
For docs: please see `README(test_map_packager).md`.

Disclaimer: Functions mostly generated by AI. Intent of this script is to be as hands-off as possible
on the implementation side and only modify it where absolutely necessary.
"""

try:
    import __tileset_parser as __tp
except ImportError:
    try:
        from . import __tileset_parser as __tp
    except ImportError:
        raise ImportError("Failed to import `__tileset_parser.py`")


import json
from pathlib import Path
import shutil
import tempfile
import zipfile
import re
import copy
import struct

# 1. Dynamically target the absolute directory of the file currently executing
current_dir = Path(__file__).resolve().parent

# 2. Bind the target asset file path permanently without context manager constraints
WZ2100_ADDON_LEV_FILEPATH = current_dir / "addon.lev"


POSITION_OFFSET = 3       # To move by "1" WZ2100 game tile, enter "128".


def write_json(path: Path, obj: dict) -> None:
    """Write a JSON file with consistent formatting."""
    with open(path, "w", encoding="utf-8") as f:
        json.dump(obj, f, indent=4)
        f.write("\n")


def read_json(path: Path) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def create_gam_json(map_width: int, map_height: int) -> dict:
    """
    Create gam.json for a Warzone 2100 map.

    Parameters
    ----------
    map_width : int
        Width of the map in tiles.
    map_height : int
        Height of the map in tiles.

    Returns
    -------
    dict
        JSON-ready dictionary.
    """
    return {
        "version": 8,
        "gameTime": 0,
        "GameType": 0,
        "ScrollMinX": 0,
        "ScrollMinY": 0,
        "ScrollMaxX": map_width - 1,
        "ScrollMaxY": map_height - 1,
        "levelName": ""
    }


def create_level_json(name: str, players: int, tileset: str) -> dict:
    """
    Create level.json for a cloned map.

    The map name and player count are incremented by one.
    For example:
        "2c-UrbanChasm" -> "3c-UrbanChasm"
        players=2 -> 3
    """
    new_players = players + 1
    new_name = f"{new_players}c-{name}"

    return {
        "name": new_name,
        "type": "skirmish",
        "players": new_players,
        "tileset": tileset,
        "author": {
            "name": "hi"
        },
        "spdx-license-id": "CC0-1.0",
        "created-date": "2010-10-18 15:16:10",
        "generator": "wzmaplib 1.2.2",
        "prior-generator": "flaME v1.10"
    }

def create_test_json():
    ### The purpose of this function is to generate custom 'gam.json' and 'level.json' files which are packaged with
    ###  the existing Warzone2100 v4.7.0 map files. It's just a test, it can be deleted.

    gam = create_gam_json(96, 96)
    level = create_level_json("UrbanChasm", 3)

    write_json(Path.cwd() / "gam.json", gam)
    write_json(Path.cwd() / "level.json", level)

##################################################################
def parse_map_folder_name(source_dir: Path) -> dict:
    """
    Validate a source map directory and extract metadata.

    Parameters
    ----------
    source_dir : Path

    Returns
    -------
    dict

    Raises
    ------
    ValueError
        If the directory name or contents are invalid.
    """

    if not source_dir.is_dir():
        raise ValueError(f"'{source_dir}' is not a directory.")

    # Parse folder name.
    match = re.fullmatch(r"(\d+)c-(.+)", source_dir.name)
    if match is None:
        raise ValueError(
            f"Folder name '{source_dir.name}' does not match '<players>c-<name>'."
        )

    source_players = int(match.group(1))
    base_name = match.group(2)

    # Validate directory contents.
    expected_files = {
        "game.map",
        "ttypes.ttp",
        "feature.json",
        "struct.json",
        "droid.json",
    }

    actual_files = {
        p.name
        for p in source_dir.iterdir()
        if p.is_file()
    }

    if actual_files != expected_files:
        missing = expected_files - actual_files
        extra = actual_files - expected_files

        messages = []

        if missing:
            messages.append(
                f"missing: {', '.join(sorted(missing))}"
            )

            raise ValueError(
                f"Invalid contents for '{source_dir.name}' ({'; '.join(messages)})."
            )

        if extra:
            messages.append(
                f"unexpected: {', '.join(sorted(extra))}"
            )

    return {
        "source_name": source_dir.name,
        "base_name": base_name,
        "source_players": source_players,
        "output_name": f"{source_players + 1}c-{base_name}",
    }


def parse_game_map(path: Path) -> tuple[int, int]:
    """
    Extract map dimensions from game.map.
    """

    with open(path, "rb") as f:
        header = f.read(16)

    if len(header) != 16:
        raise ValueError("game.map header is too short")

    magic = header[:4]

    if magic != b"map ":
        raise ValueError(
            f"Unexpected game.map header: {magic}"
        )

    version, width, height = struct.unpack(
        "<III",
        header[4:16],
    )

    return width, height


def copy_static_assets(source_dir: Path, build_dir: Path) -> None:
    """Copy assets that are not modified."""

    for filename in (
        "game.map",
        "ttypes.ttp",
        "feature.json",
    ):
        shutil.copy2(
            source_dir / filename,
            build_dir / filename,
        )


def duplicate_start_position(
    data: dict,
    source_startpos: int,
    new_startpos: int,
    key_prefix: str,
) -> None:
    """
    Duplicate / relabel all entries belonging to one start position.
    """

    next_id = 8888

    for item in list(data.values()):
        if item.get("startpos") != source_startpos:
            continue

        if item.get("name") == "A0CommandCentre":
            # this sets the start position
            new_item = copy.deepcopy(item)
            new_item["start_pos"] = new_startpos
            
            data[f"{key_prefix}_{next_id:04d}"] = new_item

            next_id += 1

        # Else, overwrite the startpos to prevent a conflict
        item["startpos"] = new_startpos

def translate_start_position(
    data: dict,
    startpos: int,
    dx: int,
    dy: int,
) -> None:
    """
    Translate all structures belonging to a start position.
    """

    for structure in data.values():
        if structure.get("startpos") != startpos:
            continue

        structure["position"][0] += dx
        structure["position"][1] += dy


def process_struct_json(src: Path, dst: Path, metadata: dict) -> None:
    data = read_json(src)

    new_player_id = metadata["source_players"]

    duplicate_start_position(
        data,
        source_startpos=0,
        new_startpos=new_player_id,
        key_prefix="structure",
    )

    translate_start_position(
        data,
        startpos=0,
        dx=POSITION_OFFSET,
        dy=POSITION_OFFSET,
    )

    write_json(dst, data)


def process_droid_json(src: Path, dst: Path, metadata: dict) -> None:
    data = read_json(src)

    new_player_id = metadata["source_players"]

    duplicate_start_position(
        data,
        source_startpos=0,
        new_startpos=new_player_id,
        key_prefix="droid",
    )

    translate_start_position(
        data,
        startpos=new_player_id,
        dx=POSITION_OFFSET,
        dy=POSITION_OFFSET,
    )

    write_json(dst, data)


def generate_metadata(build_dir: Path, metadata: dict) -> None:
    """
    Generate level.json and gam.json.
    """

    write_json(
        build_dir / "gam.json",
        create_gam_json(
            metadata["map_width"],
            metadata["map_height"],
        )
    )

    write_json(
        build_dir / "level.json",
        create_level_json(
            metadata["base_name"],
            metadata["source_players"],
            metadata["tileset"]
        ),
    )


def package_map(
    build_dir: Path,
    metadata: dict,
    output_dir: Path,
) -> Path:
    """
    Package a build directory into a .wz archive.

    Parameters
    ----------
    build_dir : Path
        Temporary directory containing the completed map.
    metadata : dict
        Map metadata returned by parse_map_folder_name().
    output_dir : Path
        Destination directory for the archive.

    Returns
    -------
    Path
        Path to the generated archive.

    Raises
    ------
    ValueError
        If packaging fails.
    """

    output_path = output_dir / f"{metadata['output_name']}.wz"

    try:
        with zipfile.ZipFile(
            output_path,
            mode="w",
            compression=zipfile.ZIP_DEFLATED,
        ) as archive:

            for file in build_dir.iterdir():
                if file.is_file():
                    archive.write(
                        file,
                        arcname=file.name,
                    )

    except Exception as e:
        raise ValueError(f"Failed to package map: {e}")

    return output_path


def repackage_map(
    source_dir: Path,
    output_dir: Path,
) -> str:
    """
    Process a single source map.

    Parameters
    ----------
    source_dir : Path
        Source map directory.
    output_dir : Path
        Directory where the generated .wz archive will be written.

    Returns
    -------
    str
        Name of the generated archive.

    Raises
    ------
    ValueError
        If any processing step fails.
    """

    output_dir.mkdir(parents=True, exist_ok=True)

    metadata = parse_map_folder_name(source_dir)

    map_width, map_height = parse_game_map(
        source_dir / "game.map"
    )

    metadata["map_width"] = map_width
    metadata["map_height"] = map_height
    metadata["tileset"] = __tp.parse_tileset_from_lev(
        addon_lev_path=WZ2100_ADDON_LEV_FILEPATH,
        map_folder_name=source_dir.name,
    )

    with tempfile.TemporaryDirectory() as temp_dir:
        build_dir = Path(temp_dir)

        # Copy static assets.
        copy_static_assets(source_dir, build_dir)

        # Process transformable assets.
        process_struct_json(
            source_dir / "struct.json",
            build_dir / "struct.json",
            metadata,
        )

        process_droid_json(
            source_dir / "droid.json",
            build_dir / "droid.json",
            metadata,
        )

        # Generate metadata files.
        generate_metadata(build_dir, metadata)

        # Package the finished map.
        output_path = package_map(
            build_dir,
            metadata,
            output_dir,
        )

    return output_path.name



if __name__ == "__main__":
    # The initial test script; runner is moved to `run_test_map_packager.py` for clarity.

    report = []

    first_source_dir = Path.cwd() / 'v4.7.0_base_maps/2c-highground'

    try:
        output = repackage_map(first_source_dir, output_dir=Path.cwd())
        report.append({
            "map": first_source_dir.name,
            "success": True,
            "error": None,
            "output": output,
        })
    except ValueError as e:
        report.append({
            "map": first_source_dir.name,
            "success": False,
            "error": str(e),
            "output": None,
        })

    print(report)