# The purpose of this script is to demonstrate a method which can be used to:
# 1. automatically run a WZ2100 bot vs bot game
# 2. save the result internally within Python for further processing

"""
== Historical Context ==

A long time ago I found that:

`   "Warzone 2100\bin\warzone2100.exe" --configdir="Warzone 2100\PRODCONFIG" --skirmish="GAMMA_HARD_COBRA_T2.json" --enableconsole --headless --autogame     `

ran allowed me to run autogames in a Windows console directly. The console output could then be saved using the "Export text" button in the Windows 11 command prompt.

Initially I tried:
- subprocess.run(... capture_output=True, text=True) 
- subprocess.run(... stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True) 
- subprocess.Popen(... stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
- winpty .spawn() (emulating a terminal internally)
and no dice. It seems like WZ2100 does not write to stdout/stderr by default using my existing `--autogame` command above.

Then I tried various combinations of these command line flags:
1. "--debugfile=blah.log"      
2. "--debug=all"                   ***
3. "----flush-debug-stderr"
but although I was able to obtain out the raw (internal) debug output in `blah.log` (when using 1. and 2. together), this did not contain the summary results table printed to the console with `--autogame`.

*** Note: to find the <flags> for the `debug=<flags>` command line argument:
1. `clparse.cpp` defines the command line functions.
2. Check --debug flag -> https://github.com/Warzone2100/warzone2100/blob/8701c62ae68ca70da43ec915cbf6776c492e6656/src/clparse.cpp#L530
3. Usage is --debug=<flag>. So what are the acceptable values of 'flag'?
4. Check function `debug_enable_switch` -> https://github.com/Warzone2100/warzone2100/blob/master/lib/framework/debug.cpp#L434
5. Then `code_part_from_str` -> https://github.com/Warzone2100/warzone2100/blob/master/lib/framework/debug.cpp#L140
6. Then `code_part_names` -> https://github.com/Warzone2100/warzone2100/blob/master/lib/framework/debug.cpp#L87C20-L127
and these are the necessary flags for 'debug=<flags>'.

Finally, I tried scraping the IDE console after subprocess.run() finished executing, which did finally work.
Disclaimer: `scrape_terminal_history()` and `clear_console()` are completely generated by AI (Gemini).
"""

import ctypes
import subprocess
import os
from typing import List

# Fold this function to hide it.
def clear_console():
    # Use 'cls' for Windows (os.name == 'nt') and 'clear' for Linux/macOS
    os.system('cls' if os.name == 'nt' else 'clear')

# Fold this function to hide it.
def scrape_terminal_history(lines_to_read):
    """
    Extracts printed text directly from the current Windows 
    console host window's screen buffer matrix.
    """
    kernel32 = ctypes.windll.kernel32
    # -11 references the standard active output device handle
    stdout_handle = kernel32.GetStdHandle(-11) 
    
    class COORD(ctypes.Structure):
        _fields_ = [("X", ctypes.c_short), ("Y", ctypes.c_short)]
        
    class SMALL_RECT(ctypes.Structure):
        _fields_ = [("Left", ctypes.c_short), ("Top", ctypes.c_short), 
                    ("Right", ctypes.c_short), ("Bottom", ctypes.c_short)]
                    
    class CONSOLE_SCREEN_BUFFER_INFO(ctypes.Structure):
        _fields_ = [("dwSize", COORD), ("dwCursorPosition", COORD),
                    ("wAttributes", ctypes.c_ushort), ("srWindow", SMALL_RECT),
                    ("dwMaximumWindowSize", COORD)]
        
    csbi = CONSOLE_SCREEN_BUFFER_INFO()
    kernel32.GetConsoleScreenBufferInfo(stdout_handle, ctypes.byref(csbi))
    
    # Calculate the bounding block to extract from based on where the cursor left off
    start_row = max(0, csbi.dwCursorPosition.Y - lines_to_read)
    read_coord = COORD(0, start_row)
    total_cells = csbi.dwSize.X * lines_to_read
    
    chars_read = ctypes.c_ulong(0)
    buffer_allocation = ctypes.create_string_buffer(total_cells)
    
    # Scrape the raw Win32 console cell text grid
    kernel32.ReadConsoleOutputCharacterA(
        stdout_handle, buffer_allocation, total_cells, read_coord, ctypes.byref(chars_read)
    )
    
    raw_text = buffer_allocation.value.decode('utf-8', errors='ignore')
    
    # Slice the continuous buffer string back into clean, individual console lines
    formatted_lines = []
    for i in range(0, len(raw_text), csbi.dwSize.X):
        line_chunk = raw_text[i:i + csbi.dwSize.X].rstrip()
        if line_chunk:  # Skip empty whitespace lines
            formatted_lines.append(line_chunk)
            
    return formatted_lines


# Inherits input parameter descriptions from the inbuilt Python `range()` function.
def generate_range(start: int, stop: int, step: int) -> List[int]:
    return list(range(start, stop, step))


def find_final_game_summary_table_index(console_history: List[str]) -> int:
    GAME_SUMMARY_TABLE_TITLE = "Game State"
    GAME_SUMMARY_TABLE_IDX = 0    # if GAME_STATE_TABLE_TEXT not found, returns the whole history

    LIST_LENGTH = len(console_history)
    REVERSED_LIST_INDEXES = generate_range(start=LIST_LENGTH-1, stop=-1, step=-1)

    for i in REVERSED_LIST_INDEXES:
        if GAME_SUMMARY_TABLE_TITLE in console_history[i]:
            GAME_SUMMARY_TABLE_IDX = i
            break
    else:
        print(f'WARNING: could not find string: "{GAME_SUMMARY_TABLE_TITLE}"')
    
    return GAME_SUMMARY_TABLE_IDX

#################################################################################################

clear_console()

# Execute normally (letting WZ write directly to the console)
command_list = [rf"Warzone 2100\bin\warzone2100.exe", rf'--configdir="Warzone 2100\PRODCONFIG"', rf'--skirmish="GAMMA_HARD_COBRA_T2.json"', rf"--enableconsole", rf"--headless", rf"--autogame"]
subprocess.run(command_list)
del command_list

# Scrapes the console output and stores it into `console_history`, then clears the console in prep for further processing
console_history = scrape_terminal_history(lines_to_read=1000)
clear_console()

# Gets the final game summary table
SUMMARY_TABLE_START_IDX = find_final_game_summary_table_index(console_history)
final_game_summary_table = console_history[SUMMARY_TABLE_START_IDX:]      
del SUMMARY_TABLE_START_IDX

# The final game summary table can now be used for further processing
print("\n\n--- Final Game Summary ---\n\n")

for line in final_game_summary_table:
    print(line)
