"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program.
	If not, see <https://www.gnu.org/licenses/>.
"""

# The purpose of this script is to create challenge json files e.g. a custom challenge .json file 
# (see `warzone2100/data/mp/tests/miza.json` or `warzone2100/data/mp/challenges/hidebehind.json` for example).
# These files should be placed in your `wz2100_config_directory/tests` folder to be read successfully by the game.

# Disclaimer: This file is mostly generated by AI.


"""
Example output `.json`:
Note: This code defines what the fields under "challenge" look like: https://github.com/Warzone2100/warzone2100/blob/8701c62ae68ca70da43ec915cbf6776c492e6656/src/multiint.cpp#L4848.

{
	"challenge": {
		"bases": 1,
		"map": "Gamma",
		"powerLevel": 2,
		"scavengers": "false",
		"techLevel": 2
	},
	"player_0": {
	    "team": 1,
	},
	"player_1": {
		"difficulty": "Medium",
		"team": 1,
		"ai": "fishbot/multiplay/skirmish/FishBot.js"
	},
	"player_2": {
		"difficulty": "Insane",
		"team": 0,
		"ai": "multiplay/skirmish/Cobra.js"
	}
}

"""

from pathlib import Path
import json
from copy import deepcopy
import CONSTANTS as C

#################################### GENERATOR FUNCTIONS ####################################

def get_uppercase_ai_name(script_name: str) -> dict:
    # Turns `Cobra.js` -> `COBRA`
    return (script_name.split(".")[0]).upper()


def create_spectator_player(team: int) -> dict:
    return {
        "difficulty": C.EASY_DIFFICULTY,
        "team": team,
        "ai": C.SPECTATOR_AI,
    }


def create_fishbot_player(team: int, difficulty: int) -> dict:
    return {
        "difficulty": difficulty,
        "team": team,
        "ai": C.FISHBOT_AI
    }


def create_opponent_player(team: int, difficulty: int, ai_name: str):
    return {
        "difficulty": difficulty,
        "team": team,
        "ai": ai_name
    }


def build_all_base_map_configs(
    map_settings: list,
    *,                  # this parameter enforces the rest of the parameters are kwargs (documentation reasons)
    bases: int,
    power_level: int,
    scavengers: int,
    tech_level: int,
) -> list:

    configs = []

    for map_info in map_settings:
        config = {
            "challenge": {
                "bases": bases,
                "map": map_info["mapName"],
                "powerLevel": power_level,
                "scavengers": scavengers,
                "techLevel": tech_level,
            },
        }

        # Intent: Rest of slots are filled with Spectator bots.
        # These spectators should be on FishBot's team because other bots may adapt to
        #   use weaker weapons to support a non-existent teammate.
        for player_id in range(0, map_info["maxPlayers"]):
            # Note: At the moment the result of this line is overwritten in both generate_ffa & generate_duel configs.
            #   This line just serves to propagate 'maxPlayers' to these functions.
            config[f"player_{player_id}"] = create_spectator_player(team=0)

        configs.append(config)

    return configs


def generate_ffa_configs(base_config: dict) -> list:
    """
    Generate one FFA test for every FishBot starting position
    on a single base configuration.
    """

    results = []

    map_name = base_config["challenge"]["map"]

    player_keys = sorted(
        key
        for key in base_config.keys()
        if key.startswith("player_") and key != "player_0"
    )

    max_players = len(player_keys)

    for fishbot_position in range(1, max_players + 1):

        config = deepcopy(base_config)

        for position in range(1, max_players + 1):

            if position == fishbot_position:
                config[f"player_{position}"] = {
                    "difficulty": C.MEDIUM_DIFFICULTY,
                    "team": position,
                    "ai": C.FISHBOT_AI,
                }
            else:
                config[f"player_{position}"] = {
                    "difficulty": C.MEDIUM_DIFFICULTY,
                    "team": position,
                    "ai": C.COBRA_AI,
                }

        results.append({
            "test_type": C.FFA,
            "map_name": map_name,
            "fishbot_position": fishbot_position,
            "opponent_position": None,
            "fishbot_difficulty": C.MEDIUM_DIFFICULTY,
            "opponent_difficulty": C.MEDIUM_DIFFICULTY,
            "config": config,
        })

    return results


def generate_duel_configs(base_config: dict) -> list:
    """
    Generate all ordered 1v1 FishBot vs Cobra tests for a single map.

    Every ordered pair of distinct player positions is generated.

    Remaining player slots remain spectators.
    """

    results = []

    map_name = base_config["challenge"]["map"]

    player_keys = sorted(
        key
        for key in base_config.keys()
        if key.startswith("player_") and key != "player_0"
    )

    max_players = len(player_keys)

    for fishbot_position in range(1, max_players + 1):

        for opponent_position in range(1, max_players + 1):

            if fishbot_position == opponent_position:
                continue

            config = deepcopy(base_config)

            for position in range(1, max_players + 1):

                if position == fishbot_position:
                    config[f"player_{position}"] = {
                        "difficulty": C.MEDIUM_DIFFICULTY,
                        "team": position,
                        "ai": C.FISHBOT_AI,
                    }
                elif position == opponent_position:
                    config[f"player_{position}"] = {
                        "difficulty": C.MEDIUM_DIFFICULTY,
                        "team": position,
                        "ai": C.COBRA_AI,
                    }
                else:
                    config[f"player_{position}"] = create_spectator_player(team=fishbot_position)

            results.append({
                "test_type": C.DUEL,
                "map_name": map_name,
                "fishbot_position": fishbot_position,
                "opponent_position": opponent_position,
                "fishbot_difficulty": C.MEDIUM_DIFFICULTY,
                "opponent_difficulty": C.MEDIUM_DIFFICULTY,
                "config": config,
            })

    return results


def make_test_filename(test: dict) -> str:
    """
    Generate a unique filename for a generated test configuration.
    """

    map_name = test["map_name"]

    if test["test_type"] == C.FFA:
        return (
            f"{map_name}"
            f"_{C.FFA}"
            f"_f{test['fishbot_position']}"
        )

    if test["test_type"] == C.DUEL:
        return (
            f"{map_name}"
            f"_{C.DUEL}"
            f"_f{test['fishbot_position']}"
            f"_c{test['opponent_position']}"
        )

    raise ValueError(f"Unknown test type: {test['test_type']}")


def write_test_configs(
    final_configs: list,
    output_dir: Path,
    manifest_path: Path,
) -> Path:
    """
    Write generated test configurations and create an immutable base manifest.

    Parameters
    ----------
    final_configs
        List of generated test configurations and metadata.
    output_dir
        Directory to write configuration files into.
    manifest_path
        Output path for the immutable base manifest.

    Returns
    -------
    Path
        Path to the written base manifest.
    """

    output_dir.mkdir(parents=True, exist_ok=True)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)

    manifest = {
        "version": 1,
        "tests": {},
    }

    for test_id, test in enumerate(final_configs):

        test_key = f"{test_id:05d}"

        descriptive_name = make_test_filename(test)
        file_name = f"{test_key}_{descriptive_name}.json"

        config_path = output_dir / file_name

        # Write config file.
        with open(config_path, "w") as f:
            json.dump(test["config"], f, indent=4)

        print(f"\t- {file_name}")

        # Copy all metadata except the full config.
        metadata = {
            key: value
            for key, value in test.items()
            if key != "config"
        }

        metadata["config_file"] = file_name

        manifest["tests"][test_key] = metadata

    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=4)

    print(f"\nSaved base manifest: {manifest_path}")

    return manifest_path


###############################################################################################

if __name__ == "__main__":
    pass

