"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program.
	If not, see <https://www.gnu.org/licenses/>.
"""

# The purpose of this script is to demonstrate a method (Python 3.11 on Windows 11) which can be used to:
# 1. automatically run a WZ2100 bot vs bot game
# 2. save the result internally within Python for further processing

r"""
~ Historical Context ~

At the start of the project I found that:

`   "Warzone 2100\bin\warzone2100.exe" --configdir="Warzone 2100\PRODCONFIG" --skirmish="GAMMA_HARD_COBRA_T2.json" --enableconsole --headless --autogame     `

ran allowed me to run autogames in a Windows console directly. The console output could then be saved using the "Export text" button in the Windows 11 command prompt.

Initially I tried:
- subprocess.run(... capture_output=True, text=True) 
- subprocess.run(... stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True) 
- subprocess.Popen(... stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
- winpty .spawn() (emulating a terminal internally)
and no dice. It seems like WZ2100 does not write to stdout/stderr by default using my existing `--autogame` command above.

Then I tried various combinations of these command line flags:
1. "--debugfile=blah.log"      
2. "--debug=all"                   ***
3. "--flush-debug-stderr"
but although I was able to obtain out the raw (internal) debug output in `blah.log` (when using 1. and 2. together), this did not contain the summary results table printed to the console with `--autogame`.

*** Note: to find the <flags> for the `debug=<flags>` command line argument:
1. `clparse.cpp` defines the command line functions.
2. Check --debug flag -> https://github.com/Warzone2100/warzone2100/blob/8701c62ae68ca70da43ec915cbf6776c492e6656/src/clparse.cpp#L530
3. Usage is --debug=<flag>. So what are the acceptable values of 'flag'?
4. Check function `debug_enable_switch` -> https://github.com/Warzone2100/warzone2100/blob/master/lib/framework/debug.cpp#L434
5. Then `code_part_from_str` -> https://github.com/Warzone2100/warzone2100/blob/master/lib/framework/debug.cpp#L140
6. Then `code_part_names` -> https://github.com/Warzone2100/warzone2100/blob/master/lib/framework/debug.cpp#L87C20-L127
and these are the necessary flags for 'debug=<flags>'.

Finally, I tried scraping the IDE console after subprocess.run() finished executing, which did finally work.

Disclaimer: most of the helper functions are generated by AI, with a few manual modifications for readability.
"""

import _telemetry

import subprocess
import os

from typing import List, Tuple
import ctypes

import pandas as pd
import json
from pathlib import Path

from time import perf_counter


#################################### HELPER FUNCTIONS ####################################

def clear_console():
    # Use 'cls' for Windows (os.name == 'nt') and 'clear' for Linux/macOS
    os.system('cls' if os.name == 'nt' else 'clear')

"""
Usage notes (`windows_scrape_terminal_history`):
    - Tested working on Win11 OS; Linux/Mac will need a different implementation for compatibility
    - If using a PyCharm IDE (e.g. 2026.1.2) you will need to enable the "Emulate Terminal In Output Console" option in
      the "Edit Configuration" / "Run Configuration" panel to get the output of --autogame to print to the console.
      VSCode appears to show the terminal output by default so no special actions may be required.
"""
def windows_scrape_terminal_history(lines_to_read):
    """
    Extracts printed text directly from the current Windows 
    console host window's screen buffer matrix.
    """
    kernel32 = ctypes.windll.kernel32
    # -11 references the standard active output device handle
    stdout_handle = kernel32.GetStdHandle(-11) 
    
    class COORD(ctypes.Structure):
        _fields_ = [("X", ctypes.c_short), ("Y", ctypes.c_short)]
        
    class SMALL_RECT(ctypes.Structure):
        _fields_ = [("Left", ctypes.c_short), ("Top", ctypes.c_short), 
                    ("Right", ctypes.c_short), ("Bottom", ctypes.c_short)]
                    
    class CONSOLE_SCREEN_BUFFER_INFO(ctypes.Structure):
        _fields_ = [("dwSize", COORD), ("dwCursorPosition", COORD),
                    ("wAttributes", ctypes.c_ushort), ("srWindow", SMALL_RECT),
                    ("dwMaximumWindowSize", COORD)]
        
    csbi = CONSOLE_SCREEN_BUFFER_INFO()
    kernel32.GetConsoleScreenBufferInfo(stdout_handle, ctypes.byref(csbi))
    
    # Calculate the bounding block to extract from based on where the cursor left off
    start_row = max(0, csbi.dwCursorPosition.Y - lines_to_read)
    read_coord = COORD(0, start_row)
    total_cells = csbi.dwSize.X * lines_to_read
    
    chars_read = ctypes.c_ulong(0)
    buffer_allocation = ctypes.create_string_buffer(total_cells)
    
    # Scrape the raw Win32 console cell text grid
    kernel32.ReadConsoleOutputCharacterA(
        stdout_handle, buffer_allocation, total_cells, read_coord, ctypes.byref(chars_read)
    )
    
    raw_text = buffer_allocation.value.decode('utf-8', errors='ignore')
    
    # Slice the continuous buffer string back into clean, individual console lines
    formatted_lines = []
    for i in range(0, len(raw_text), csbi.dwSize.X):
        line_chunk = raw_text[i:i + csbi.dwSize.X].rstrip()
        if line_chunk:  # Skip empty whitespace lines
            formatted_lines.append(line_chunk)
            
    return formatted_lines


# Inherits input parameter descriptions from the inbuilt Python `range()` function.
def generate_range(start: int, stop: int, step: int) -> List[int]:
    return list(range(start, stop, step))


def find_final_game_summary_table_index(console_history: List[str]) -> int:
    GAME_SUMMARY_TABLE_TITLE = "Game State"
    GAME_SUMMARY_TABLE_IDX = 0    # if GAME_STATE_TABLE_TEXT not found, returns the whole history

    LIST_LENGTH = len(console_history)
    REVERSED_LIST_INDEXES = generate_range(start=LIST_LENGTH-1, stop=-1, step=-1)

    for i in REVERSED_LIST_INDEXES:
        if GAME_SUMMARY_TABLE_TITLE in console_history[i]:
            GAME_SUMMARY_TABLE_IDX = i
            break
    else:
        print(f'WARNING: could not find string: "{GAME_SUMMARY_TABLE_TITLE}"')
    
    return GAME_SUMMARY_TABLE_IDX


def print_game_summary(game_summary_table: List[str]) -> None:
    print("\n\n--- Final Game Summary ---\n\n")
    for line in game_summary_table:
        print(line)


"""
Usage notes (`extract_stats_from_summary_table`):
This script ignores the 'Player' that is force-added to challenge maps.
"""
def extract_stats_from_summary_table(summary_table: List[str]) -> pd.DataFrame:
    """
    Extract player summary rows from game output.

    Expected dataframe columns:
        player_id      int
        name           str
        extract_power  int
        units_killed   int
        structures     int
        factories      int
        research       int
        units_alive    int
        power          int
        defeated       bool
    """

    rows = []

    for line in summary_table:
        if "|" not in line:
            continue

        parts = [p.strip() for p in line.split("|")]

        # Skip malformed rows
        if len(parts) < 7:
            continue

        # Skip table headers
        if parts[0] in {"#", "--"}:
            continue

        try:
            player_id = int(parts[0])
            name = parts[1]

            # Ignore observer/player row
            if name.lower() == "player":
                continue

            extract_power = int(parts[2])
            units_killed = int(parts[3])

            # Example: "51 (5/4)"
            struct_text = parts[4]

            structures_part, sub_part = struct_text.split("(")

            structures = int(structures_part.strip())

            sub_part = sub_part.replace(")", "")
            factories, research = map(int, sub_part.split("/"))

            units_alive = int(parts[5])
            power = int(parts[6])

            defeated = (
                len(parts) > 7 and parts[7].lower() == "x"
            )

            rows.append({
                "player_id": player_id,
                "name": name,
                "extract_power": extract_power,
                "units_killed": units_killed,
                "structures": structures,
                "factories": factories,
                "research": research,
                "units_alive": units_alive,
                "power": power,
                "defeated": defeated,
            })

        except (ValueError, IndexError):
            continue

    return pd.DataFrame(rows)


def append_match(df: pd.DataFrame, path: Path) -> None:
    records = df.to_dict(orient="records")

    append_records(records, path)


def append_records(records: List[dict], path: Path) -> None:
    """Appends records to a .jsonl file, flushed to disk so an interrupted batch keeps what it had."""
    with open(path, "a") as f:
        for record in records:
            f.write(json.dumps(record) + "\n")

        f.flush()
        os.fsync(f.fileno())


def telemetry_path_for(in_progress_file_path: Path) -> Path:
    """
    Telemetry is written alongside the results file, e.g. `00042.jsonl` -> `00042.tel.jsonl`.

    Keeping it in a separate file means telemetry can never disturb the existing win/loss results
    schema, and `filter_completed_tests()` in `run_tests.py` still resumes off the results file.
    """
    return in_progress_file_path.with_suffix(".tel.jsonl")


#################################### TEST RUNNERS ####################################

def run_autogame(commands: List[str]) -> Tuple[List[str], List[dict]]:
    # Execute normally (let WZ write directly to the console)
    TIMEOUT_SECONDS = 1200
    subprocess.run(commands, timeout=TIMEOUT_SECONDS)        # blocking (only returns once the process is finished)
    del TIMEOUT_SECONDS, commands

    # Scrapes the console output and stores it into `console_history`, then clears the console in prep for further processing
    console_history = windows_scrape_terminal_history(lines_to_read=1000)

    # Gets the final game summary table
    summary_table_start_idx = find_final_game_summary_table_index(console_history)
    final_game_summary_table = console_history[summary_table_start_idx:]
    del summary_table_start_idx

    # Gets FishBot's telemetry. Unlike the summary table this is emitted throughout the game, so the
    # whole console history is scanned rather than just the tail. Empty unless `TELEMETRY_ON` is set
    # in the FishBot copy under test.
    telemetry_events = _telemetry.extract_telemetry_events(console_history)

    return final_game_summary_table, telemetry_events


def run_tests(test_file_name: str, in_progress_file_path: Path, cycles: int, debug_mode: bool=False) -> float:
    # Command line parameters: https://github.com/Warzone2100/warzone2100/blob/ebeaaa7958f35879eea7b57474eff0c89aa4fb03/src/clparse.cpp#L21

    AUTOGAME_COMMAND = [
        rf"..\Warzone 2100\bin\warzone2100.exe",        # assumes WZ2100 is installed in `fishbot/Warzone 2100`
        rf'--configdir="..\Warzone 2100\PRODCONFIG"',   # assumes that the mod is loaded in a "PRODCONFIG" subfolder of the WZ2100 install location e.g. `fishbot/Warzone 2100/PRODCONFIG`
        rf'--skirmish="{test_file_name}"',              # a custom challenge .json file loaded into `configdir/tests` (see `warzone2100/data/mp/tests/miza.json` for an example). The test file must be added to the 'tests' folder: https://github.com/Warzone2100/warzone2100/blob/8701c62ae68ca70da43ec915cbf6776c492e6656/src/multiint.cpp#L526
        rf"--enableconsole",                            # creates a console (this is where the Game State summary is printed)
        rf"--headless",                                 # runs the program without a GUI
        rf"--autogame",                                 # automatically runs the game
        rf"--nosound"                                   # removes sound from autogames
    ]

    print_iteration = lambda j: print(f"\n\n Iteration {j + 1} \n\n")

    # Run the test
    TIME_STARTED = perf_counter()

    for i in range(cycles):
        clear_console()
        print_iteration(i)

        try:
            final_summary_table, telemetry_events = run_autogame(AUTOGAME_COMMAND)
        except subprocess.TimeoutExpired:
            print(f"Timed out - Terminated iteration {i} early")
            continue
        except KeyboardInterrupt:
            print(f"Keyboard Interrupt - Terminated iteration {i} early")
            continue

        if debug_mode:
            clear_console()
            print_iteration(i)
            print_game_summary(final_summary_table)
            ADD_DEBUG_BREAKPOINT_HERE_TO_SEE_THE_EXTRACTED_RESULTS_TABLE = 1

        stats = extract_stats_from_summary_table(final_summary_table)
        stats["match_id"] = i   # Record test metadata for batch processing later

        ADD_DEBUG_BREAKPOINT_HERE_TO_SEE_STATS_AS_DATAFRAME = 1

        append_match(df=stats, path=in_progress_file_path)

        # Telemetry goes to its own file so it cannot disturb the results schema above.
        # This is empty (and the file is not created) unless `TELEMETRY_ON` is set in the bot under test.
        if telemetry_events:
            for event in telemetry_events:
                event["match_id"] = i

            append_records(telemetry_events, telemetry_path_for(in_progress_file_path))

    TIME_ENDED = perf_counter()
    round_to_2dp = lambda x: round(x, 2)

    clear_console()
    SECS_TO_COMPLETE = round_to_2dp(TIME_ENDED - TIME_STARTED)
    MINS_TO_COMPLETE = round_to_2dp(SECS_TO_COMPLETE / 60.0)
    print(f"\nFinished {cycles} tests in {SECS_TO_COMPLETE} seconds ({MINS_TO_COMPLETE} minutes)")

    return MINS_TO_COMPLETE

#################################### MAIN ####################################

if __name__ == "__main__":
    """
    Functions:
    1. Run autogame
    2. Scrape console + store into dataframe
    3. Convert dataframe + test metadata to jsonl (storing the intermediate result for data safety in case of interruptions)
    
    Note: The `results.jsonl` file will be processed back into a dataframe by a downstream processing script.
    
    The jsonl pipeline is picked because its a good compromise between code complexity, speed & human-readability.
    
     1. Writing to .log/.txt (although faster) requires a custom parser & the performance improvement is minimal 
     for this application (the tests can take up to ~5min each; saving 0.5 seconds in the parsing stage doesn't make a material difference).
     
     2. Writing to Excel (as .xlsx or .csv) adds unnecessary code complexity.
    """

    clear_console()

    ######## PROGRAM CONFIGURATION ########

    TEST_FILE_NAME = "GAMMA_1_2_COBRA_HARD_T2.json"        # make sure that the json file exists in `%Warzone Configuration Directory%/tests`.
    NUM_CYCLES_PER_TEST = 1
    DEBUG_ON = False

    COMMIT_SHA = """
    3781360b96ba82f5e096bdde6868a8764f3522fb
    """

    # Reminder: remove any previous .jsonl files if necessary

    # Important Note: The `windows_scrape_terminal_history` function is the core technical component of this script.
    # This function is platform (OS) & IDE dependent - please see the usage notes above this function.

    # The results parser (extract_stats_from_summary_table) also assumes that each row is unbroken (no word wrap).
    # To work around this, every time PyCharm is opened, we can either:
    # 1. Minimise the console so no word wrap is required
    # 2. Undock the console and enlarge it so the Game Summary table does not wrap onto new lines.

    # === RUN CONFIGURATION CHECKS (PyCharm) ===
    # 1. Check folder: `fishbot/tests` is set as the current working directory.
    # 2. If using a PyCharm IDE (e.g. 2026.1.2), you will need to enable the "Emulate Terminal In Output Console" option in
    #       the "Edit Configuration" / "Run Configuration" panel.
    #       This is to allow the output of --autogame to be printed to the console.
    #       VSCode appears to show the terminal output by default, so no special actions may be required for VSCode.

    ######## END PROGRAM CONFIGURATION ########

    SHORT_SHA = COMMIT_SHA.lstrip()[:7]
    OUTPUT_FILE_NAME = f"{SHORT_SHA},{TEST_FILE_NAME},{NUM_CYCLES_PER_TEST}G.jsonl"
    OUTPUT_FILE_PATH = Path.cwd() / OUTPUT_FILE_NAME

    mins_to_complete = run_tests(
        test_file_name=TEST_FILE_NAME,
        in_progress_file_path=OUTPUT_FILE_PATH,
        cycles=NUM_CYCLES_PER_TEST,
        debug_mode=DEBUG_ON
    )

    print(f"Caller: completed in {mins_to_complete} minutes")
