"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program.
	If not, see <https://www.gnu.org/licenses/>.
"""

# The purpose of this script is to create challenge json files e.g. a custom challenge .json file 
# (see `warzone2100/data/mp/tests/miza.json` or `warzone2100/data/mp/challenges/hidebehind.json` for example).
# These files should be placed in your `wz2100_config_directory/tests` folder to be read successfully by the game.

# Disclaimer: This file is mostly generated by AI.


"""
Example output `.json`:
Note: This code defines what the fields under "challenge" look like: https://github.com/Warzone2100/warzone2100/blob/8701c62ae68ca70da43ec915cbf6776c492e6656/src/multiint.cpp#L4848.

{
	"challenge": {
		"bases": 1,
		"map": "Gamma",
		"powerLevel": 2,
		"scavengers": "false",
		"techLevel": 2
	},
	"player_0": {
	    "team": 1,
	},
	"player_1": {
		"difficulty": "Medium",
		"team": 1,
		"ai": "fishbot/multiplay/skirmish/FishBot.js"
	},
	"player_2": {
		"difficulty": "Insane",
		"team": 0,
		"ai": "multiplay/skirmish/Cobra.js"
	}
}

"""

import json
import CONSTANTS as C

#################################### GENERATOR FUNCTIONS ####################################

def get_uppercase_ai_name(script_name: str):
    # Turns `Cobra.js` -> `COBRA`
    return (script_name.split(".")[0]).upper()


def create_empty_player(team: int):
    return {
        "difficulty": C.EASY_DIFFICULTY,
        "team": team,
        "ai": C.SPECTATOR_AI,
    }


def create_fishbot_player(team: int, difficulty: int):
    return {
        "difficulty": difficulty,
        "team": team,
        "ai": C.FISHBOT_AI
    }


def create_cobra_player(team: int, difficulty: int):
    return {
        "difficulty": difficulty,
        "team": team,
        "ai": C.COBRA_AI
    }


def create_challenge_from_template(challenge_name: str, challenge_version: int, map_name: str, total_players: int,
                                   bases: int, power_level: int, scavengers: int, tech_level: int,
                                   fishbot_position: int, fishbot_difficulty: str, fishbot_factory,
                                   opponent_position: int, opponent_difficulty: str, opponent_factory):
    data = {
        "challenge": {
            "bases": bases,
            "map": map_name,
            "powerLevel": power_level,
            "scavengers": scavengers,
            "techLevel": tech_level,

            "name": challenge_name,
            "version": challenge_version
        }
    }

    # The "OPPONENT TEAM" should only contain the opponent player(s).
    # In a 1v1 - this means that the opponent will not activate any 'team-related' code, which may put it at a disadvantage.
    # e.g. Cobra begins using artillery only.
    OPPONENT_TEAM = 0
    FISHBOT_TEAM = 1        # this team should contain FishBot & all spectator players.

    # Fill all slots with empty players
    for i in range(total_players):
        data[f"player_{i}"] = create_empty_player(team=FISHBOT_TEAM)

    # Insert FishBot
    data[f"player_{fishbot_position}"] = fishbot_factory(
        team=FISHBOT_TEAM,
        difficulty=fishbot_difficulty
    )

    # Insert Cobra
    data[f"player_{opponent_position}"] = opponent_factory(
        team=OPPONENT_TEAM,
        difficulty=opponent_difficulty
    )

    return data


def generate_json_test_data(skirmish_settings, map_settings):

    generated_test_data = []

    # SKIRMISH INFO
    BASES: int = skirmish_settings['bases']
    POWER_LEVEL: int = skirmish_settings['powerLevel']
    SCAVENGERS: int = skirmish_settings['scavengers']
    TECH_LEVEL: int = skirmish_settings['techLevel']

    # FISHBOT INFO
    FISHBOT_DIFFICULTY: str = skirmish_settings['fishbotDifficulty']
    fishbot_factory = create_fishbot_player

    # 'OPPONENT' INFO
    OPPONENT_NAME: str = get_uppercase_ai_name(skirmish_settings['opponentName'])
    OPPONENT_DIFFICULTY: str = skirmish_settings['opponentDifficulty']
    opponent_factory = create_cobra_player         # todo -> extend cobra factory into others

    for m in map_settings:
        # MAP INFO
        MAP_NAME: str = m['mapName']
        MAX_PLAYERS: int = m['maxPlayers']

        # POSITION INFO (1v1 ONLY)
        POSITION1: int = m['fishbot_position']
        POSITION2: int = m['opponent_position']

        POSITIONS = [POSITION1, POSITION2]
        NUM_POSITIONS = len(POSITIONS)

        # Creates two copies with positions swapped (only works for 1v1)
        for i in range(NUM_POSITIONS):

            FISHBOT_POSITION = POSITIONS[i % NUM_POSITIONS]
            OPPONENT_POSITION = POSITIONS[(i+1) % NUM_POSITIONS]

            FILE_NAME = f"{MAP_NAME.upper()}_{FISHBOT_POSITION}_{OPPONENT_POSITION}_{OPPONENT_NAME}_{OPPONENT_DIFFICULTY.upper()}_T{TECH_LEVEL}.json"
            FILE_VER = 1

            challenge_data = create_challenge_from_template(
                # Map & game setup
                challenge_name=FILE_NAME, challenge_version=FILE_VER, map_name=MAP_NAME, total_players=MAX_PLAYERS,
                bases=BASES, power_level=POWER_LEVEL, scavengers=SCAVENGERS, tech_level=TECH_LEVEL,
                # Player setup
                fishbot_position=FISHBOT_POSITION, fishbot_difficulty=FISHBOT_DIFFICULTY, fishbot_factory=fishbot_factory,
                opponent_position=OPPONENT_POSITION, opponent_difficulty=OPPONENT_DIFFICULTY, opponent_factory=opponent_factory,
            )

            generated_test_data.append({'file_name': FILE_NAME, 'raw_data': challenge_data})

    return generated_test_data


#################################### SAVE FUNCTIONS ####################################

def save_challenge_files(generated_test_data: list, output_folder_path: str):

    print(f"Saving challenge files to: `{output_folder_path}`")

    for d in generated_test_data:
        FILE_NAME = d["file_name"]
        DATA = d["raw_data"]

        FILE_PATH = rf"{output_folder_path}/{FILE_NAME}"

        with open(FILE_PATH, "w") as f:
            json.dump(DATA, f, indent=4)

        print(f"\t - `{FILE_NAME}` saved.")


###############################################################################################


if __name__ == "__main__":

    import set_autogame_config as cfg

    from os import path as path
    DEV_CONFIG_PATH = path.expandvars(r"C:\Users\%USERNAME%\OneDrive\Documents\wz2100_config_dir\tests")
    PROD_CONFIG_PATH = r"..\Warzone 2100\PRODCONFIG\tests"

    #################################### USER CONFIG START ####################################

    SKIRMISH_SETTINGS, MAP_SETTINGS = cfg.generate_1v1_cobra_hard()

    OUTPUT_FOLDER_PATH = PROD_CONFIG_PATH

    #################################### USER CONFIG END ####################################

    json_test_data = generate_json_test_data(skirmish_settings=SKIRMISH_SETTINGS, map_settings=MAP_SETTINGS)
    save_challenge_files(generated_test_data=json_test_data, output_folder_path=OUTPUT_FOLDER_PATH)

