"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program. 
	If not, see <https://www.gnu.org/licenses/>.
"""

# Disclaimer: This script is generated by AI.

from collections import Counter
import matplotlib.pyplot as plt

timeslots = [ 1,2,3,4,5,6,6,7,7,8,9,11,12,13,14,15,16,17,19,21,22,23,24,25,26,26,27,27,29,31,32,33,34,35,36,37,38,39,41,42,43,44,45,46,46,47,47,49,51,52,53,54,55,56,57,59,61,62,63,64,65,66,66,67,67,68,69,71,72,73,74,75,76,77,79,81,82,83,84,85,86,86,87,87,89,91,92,93,94,95,96,97,98,99,99,101,102,103,104,105,106,106,107,107,109,111,112,113,114,115,116,117,119,121,122,123,124,125,126,126,127,127,128,129,131,132,133,134,135,136,137,139,141,142,143,144,145,146,146,147,147,149,151,152,153,154,155,156,157,158,159,161,162,163,164,165,166,166,167,167,169,171,172,173,174,175,176,177,179,181,182,183,184,185,186,186,187,187,188,189,191,192,193,194,195,196,197,199,201,202,203,204,205,206,206,207,207,209,211,212,213,214,215,216,217,218,219,221,222,223,224,225,226,226,227,227,229,231,232,233,234,235,236,237,239,241,242,243,244,245,246,246,247,247,248,249,249,251,252,253,254,255,256,257,259,261,262,263,264,265,266,266,267,267,269,271,272,273,274,275,276,277,278,279,281,282,283,284,285,286,286,287,287,289,291,292,293,294,295,296,297,299]

TOTAL_SLOTS = len(timeslots)

# Count tasks per slot
slot_counts = Counter(timeslots)

# Fill missing slots with 0
tasks_per_slot = [slot_counts.get(i, 0) for i in range(TOTAL_SLOTS)]

# Frequency table (frames with N tasks)
load_frequency = Counter(tasks_per_slot)

print("Frames per task count:")
for tasks, frames in sorted(load_frequency.items()):
    print(f"{frames} = {tasks} task")


# plots side-by-side:
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.hist(timeslots, bins=range(TOTAL_SLOTS+1))
plt.title("Timeslot Distribution")

plt.subplot(1,2,2)
plt.hist(tasks_per_slot, bins=range(max(tasks_per_slot)+2))
plt.title("Tasks Per Frame")

plt.show()