"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program. 
	If not, see <https://www.gnu.org/licenses/>.
"""

# Disclaimer: This script is generated by AI.

from collections import Counter
import matplotlib.pyplot as plt

timeslots = [0,1,2,3,5,5,6,7,7,8,10,11,11,12,13,13,15,15,16,17,18,20,21,22,23,25,25,26,27,27,28,30,31,31,32,33,35,35,36,37,38,40,41,42,43,45,45,46,47,47,48,50,51,51,52,53,55,55,56,57,58,60,61,62,63,65,65,66,67,67,68,70,71,71,72,73,75,75,76,77,78,80,81,82,83,85,85,86,87,87,88,90,91,91,92,93,95,95,96,97,98,100,101,102,103,105,105,106,107,107,108,110,111,111,112,113,115,115,116,117,118,120,121,122,123,125,125,126,127,127,128,130,131,131,132,133,135,135,136,137,138,140,141,142,143,145,145,146,147,147,148,150,151,151,152,153,155,155,156,157,158,160,161,162,163,163,165,165,166,167,167,168,170,171,171,172,173,175,175,176,177,178,180,181,182,183,185,185,186,187,187,188,190,191,191,192,193,195,195,196,197,198,200,201,202,203,205,205,206,207,207,208,210,211,211,212,213,215,215,216,217,218,220,221,222,223,225,225,226,227,227,228,230,231,231,232,233,235,235,236,237,238,240,241,242,243,245,245,246,247,247,248,250,251,251,252,253,255,255,256,257,258,260,261,262,263,265,265,266,267,267,268,270,271,271,272,273,275,275,276,277,278,280,281,282,283,285,285,286,287,287,288,290,291,291,292,293,295,295,296,297,298]

TOTAL_SLOTS = len(timeslots)

# Count tasks per slot
slot_counts = Counter(timeslots)

# Fill missing slots with 0
tasks_per_slot = [slot_counts.get(i, 0) for i in range(TOTAL_SLOTS)]

# Frequency table (frames with N tasks)
load_frequency = Counter(tasks_per_slot)

print("Frames per task count:")
for tasks, frames in sorted(load_frequency.items()):
    print(f"{frames} = {tasks} task")


# plots side-by-side:
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.hist(timeslots, bins=range(TOTAL_SLOTS+1))
plt.title("Timeslot Distribution")

plt.subplot(1,2,2)
plt.hist(tasks_per_slot, bins=range(max(tasks_per_slot)+2))
plt.title("Tasks Per Frame")

plt.show()