"""
This is a test file to test my binary heap implementation.
This entire script is generated by AI (ChatGPT & Gemini).
"""

import heapq
import random
import time
from binary_heap_test import MyBinaryMinHeap as BinaryHeap

import functools
import inspect

def log_all_methods(cls):
    """
    This function (generated by Gemini) prints out the currently executing function in the console.
    """
    # Iterate through all attributes of the class
    for name, method in inspect.getmembers(cls, predicate=inspect.isfunction):
        # Define the wrapper logic
        def make_wrapper(m):
            @functools.wraps(m)
            def wrapper(*args, **kwargs):
                print(f"Currently inside: {m.__name__}")
                return m(*args, **kwargs)

            return wrapper

        # Replace the original method with the wrapped version
        setattr(cls, name, make_wrapper(method))
    return cls


# Disclaimer: This entire class was generated by ChatGPT.
@log_all_methods
class BinaryHeapTests:
    """
    These tests are generated by ChatGPT.
    """

    @staticmethod
    def run_all():
        BinaryHeapTests.test_empty_heap()
        BinaryHeapTests.test_single_item()

        BinaryHeapTests.test_ascending_inserts()
        BinaryHeapTests.test_descending_inserts()
        BinaryHeapTests.test_random_sorting()

        BinaryHeapTests.test_against_heapq()

        BinaryHeapTests.benchmark_against_naive()

        print("All tests passed.")

    @staticmethod
    def test_empty_heap():

        heap = BinaryHeap()

        assert len(heap) == 0
        assert heap.peek() is None
        assert heap.pop() is None

    @staticmethod
    def test_single_item():
        heap = BinaryHeap()

        heap.push(5)

        assert len(heap) == 1
        assert heap.peek() == 5
        assert heap.pop() == 5
        assert heap.pop() is None


    @staticmethod
    def test_ascending_inserts():
        heap = BinaryHeap()

        for x in [1, 2, 3, 4, 5]:
            heap.push(x)

        result = []

        while len(heap):
            result.append(heap.pop())

        assert result == [1, 2, 3, 4, 5]

    @staticmethod
    def test_descending_inserts():
        heap = BinaryHeap()

        for x in [5, 4, 3, 2, 1]:
            heap.push(x)

        result = []

        while len(heap):
            result.append(heap.pop())

        assert result == [1, 2, 3, 4, 5]

    @staticmethod
    def test_random_sorting():
        random.seed(123)

        heap = BinaryHeap()

        data = [random.randint(0, 1000) for _ in range(100)]

        for x in data:
            heap.push(x)

        result = []

        while len(heap):
            result.append(heap.pop())

        assert result == sorted(data)



    @staticmethod
    def test_against_heapq():
        random.seed(123)

        my_heap = BinaryHeap()
        ref_heap = []

        for _ in range(10000):

            do_push = (
                len(ref_heap) == 0
                or random.random() < 0.7
            )

            if do_push:
                value = random.randint(0, 10000)

                my_heap.push(value)
                heapq.heappush(ref_heap, value)

            else:
                assert my_heap.pop() == heapq.heappop(ref_heap)

        while ref_heap:
            assert my_heap.pop() == heapq.heappop(ref_heap)

        assert my_heap.pop() is None


    @staticmethod
    def benchmark_against_naive():

        N = 10000

        data = [
            random.randint(0, 100000)
            for _ in range(N)
        ]

        #
        # Binary heap
        #

        heap = BinaryHeap()

        t0 = time.perf_counter()

        for x in data:
            heap.push(x)

        while len(heap):
            heap.pop()

        heap_time = time.perf_counter() - t0

        #
        # Naive list
        #

        lst = []

        t0 = time.perf_counter()

        for x in data:
            lst.append(x)

        while lst:
            idx = min(
                range(len(lst)),
                key=lambda i: lst[i]
            )

            lst.pop(idx)

        naive_time = time.perf_counter() - t0

        print()
        print("Benchmark")
        print(f"Heap:  {heap_time:.3f}s")
        print(f"Naive: {naive_time:.3f}s")


if __name__ == '__main__':
    BinaryHeapTests.run_all()