"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program. 
	If not, see <https://www.gnu.org/licenses/>.
"""

# Disclaimer: this file was generated by AI (Gemini).
import json
import numpy as np
import matplotlib.pyplot as plt

####################################################################

# FILE_NAME = "gamma_height"
# FILE_NAME = "bloat_height"
FILE_NAME = "bloat_terrainType"

####################################################################
with open(rf'.\python_helper_scripts\map_analysis\{FILE_NAME}.json', 'r') as f:
    raw_data = json.load(f)

# Convert strings to 2D numeric array
data = np.array([list(map(float, row.split(','))) for row in raw_data])

# Plot heatmap
plt.imshow(data, cmap='plasma', aspect='auto')  # red=high, blue=low
plt.colorbar(label='Value')

plt.title(f"2D Heatmap of '{FILE_NAME}'")
plt.xlabel("X")
plt.ylabel("Y")

plt.show()