"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program. 
	If not, see <https://www.gnu.org/licenses/>.
"""

# Disclaimer: this file was generated by AI (Gemini).

# The purpose of this file is to serialise raw data strings gathered from the game engine into JSON.
# This avoids storing giant arrays of numbers inside python scripts, separating data from functionality.

import json

FILE_NAME = "test"

data_strings = [

]

with open(rf'.\python_helper_scripts\map_analysis\{FILE_NAME}.json', 'w') as f:
    json.dump(data_strings, f)
