/*
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program. 
	If not, see <https://www.gnu.org/licenses/>.
*/

/////////////////////////////////    Debugging functions    /////////////////////////////////

function getCurrGameTimeMinSec() {
	const MS_PER_MINUTE = 60000;

	const mins = String(Math.floor(gameTime / MS_PER_MINUTE)).padStart(2, '0'); 
	const secs = String(Math.floor((gameTime % MS_PER_MINUTE) / 1000)).padStart(2, '0');;
	return `${mins}:${secs}`;
}

/**
 * Custom debug which prefixes the inbuilt `debug()` with playerID & a readable game time (format: `mm:ss`).
 * @param {string[]} values
 * @returns {void}
 */
function deb(...values) {
	const DEBUG_PREFIX = `F${me}:  ${getCurrGameTimeMinSec()}:  `;
	debug(`${DEBUG_PREFIX} ${values}`);
}

/**
 * Custom debug which prefixes the inbuilt `debug()` with: playerID, a readable game time (format: `mm:ss`) and "WARNING".
 * @param  {...any} values 
 */
function warn(...values) {
	const DEBUG_PREFIX = `F${me}:  ${getCurrGameTimeMinSec()}:  WARNING  `;
	debug(`${DEBUG_PREFIX} ${values}`);
}

/**
 * Highlights a 2x2 area centered on a specified tile coordinate.
 * @param {number} x 
 * @param {number} y 
 * @returns {void}
 */
function markTile(x, y) {
	hackMarkTiles(x, y, x+2, y+2);
}

/**
 * More convenient version of the inbuilt `profile` function.
 * @param {Function} callback 
 * @param {string} suffix
 * @example
 * ```
 * const functionUnderTest = () => myFunc(param1, param2, ...);
 * const result = fprof(functionUnderTest);
 * ```
 * Will show up in log under `__functionUnderTest`. Rename `functionUnderTest` to whatever you want.
 * 
 * When you want to remove the profiler, no need to rewrite the function definition; just write `result = myFunc(param1, param2, ...)`.
 */
function fprof(callback, suffix="") {

	const logFileFuncName = `__${callback.name}${suffix}`;		// this should have a unique name to avoid overwriting existing functions

	globalThis[logFileFuncName] = callback;		// overwrite callback reference since this might change with changing arguments

	return profile(logFileFuncName);
}

/////////////////////////////////    Math functions    /////////////////////////////////

//  These functions should only use the standard inbuilt JS libraries.

/**
 * Calculates the median value of a numeric input array (generated by ChatGPT).
 * @param {number[]} arr
 * @returns {number?} array median (will return undefined if `arr` is empty!)
 */
function arrayMedian(arr) {
	if (arr.length === 0) {
		warn(`Array length passed to "arrayMedian()" is 0. Will return "undefined".`);
	}
	const sorted = [...arr].sort((a, b) => a - b);
	const mid = Math.floor(sorted.length / 2);
	return sorted.length % 2
		? sorted[mid]
		: (sorted[mid - 1] + sorted[mid]) / 2;
}

/**
 * Generates an array of integers of length `stopNum`, starting with `0` and ending at integer `stopNum - 1`.
 * e.g. `generateRange(5)` produces `[0, 1, 2, 3, 4]`. 
 * @param {number} stopNum length of the array
 * @returns {number[]} array of integers starting with `0` and ending at `stopNum - 1`.
 */ 
function generateRange(stopNum) {
	let numbers = [];
	for (let i=0; i < stopNum; i++) {
		numbers.push(i);
	}
	return numbers;
}

/** 
 * More computationally efficient than `distance()` - use this where order matters, but magnitude does not. 
 * @param {number} x1 
 * @param {number} x2 
 * @param {number} y1 
 * @param {number} y2 
 * @returns {number}
 */
function distSq(x1, x2, y1, y2) {
	return (x1-x2)**2 + (y1-y2)**2;
}

/**
 * Clamps a numeric value between in a provided minimum value `min` and maximum value `max`.
 * @param {number} value 
 * @param {number} min 
 * @param {number} max 
 * @returns {number}
 */
function clampValue(value, min, max) {
	return Math.min(Math.max(value, min), max);
}

/**
 * Converts a number `n` to its binary string representation (to 20 bits).
 * @param {number} n integer
 * @returns {string} binary string representation (to 20 bits) e.g. `"00001000010000100001"`
 */
function toBinary20(n) {
	return n.toString(2).padStart(20, '0');
}

/**
 * Converts a number into its ordinal string representation (e.g. 1 to "1st").
 *
 * @param {number} n positive integer
 * @returns {string} The number appended with the correct ordinal suffix (`st`, `nd`, `rd`, or `th`).
 * 
 * @example
 * getOrdinal(1);	// returns "1st"
 * getOrdinal(22);	// returns "22nd"
 * getOrdinal(3);	// returns "3rd"
 * getOrdinal(13);	// returns "13th"
 */
function getOrdinal(n) {
	const s = ["th", "st", "nd", "rd"];
	const v = n % 100;
	return n + (s[(v - 20) % 10] || s[v] || s[0]);
};


/**
 * Returns `true` if `variable` is either `null` or `undefined`, otherwise, returns `false`.
 * @param {any} variable 
 * @returns {boolean} 
 */
function defined(variable) { 
	if (typeof variable !== "undefined") {
		if (variable !== null) {
			return true;
		}
	}
	return false;
}

/**
 * This function implements a 2D-array.
 * 
 * This implementation is used to store the grid cells representation of the map because:
 *  - ease of use when searching nearby sectors (indices are already numeric)
 *  - numeric indices are more efficient than constructing a string to index a grid entry
 * @param {number} numXCells
 * @param {number} numYCells
 * @param {function} cellFactory 
 * @returns {Array[]} 2D array (integer indexed)
 */
function create2DGrid(numXCells, numYCells, cellFactory) {

	let grid = new Array(numXCells);

	for (let x=0; x<numXCells; x++) {
		grid[x] = new Array(numYCells);

		for (let y=0; y<numYCells; y++) {
			grid[x][y] = cellFactory(x, y);
		}
	}

	return grid;
}

/**
 * Returns an array of [x, y] coordinates from start to goal inclusive (Bresenham's Line Algorithm).
 * Disclaimer: This function is generated by AI (ChatGPT).
 */
function drawLine(startX, startY, endX, endY) {
    const points = [];

    let x = startX;
    let y = startY;

    const dx = Math.abs(endX - startX);
    const dy = Math.abs(endY - startY);

    const sx = startX < endX ? 1 : -1;
    const sy = startY < endY ? 1 : -1;

    let err = dx - dy;

    while (true) {
        points.push([x, y]);

        if (x === endX && y === endY) {
            break;
        }

        const e2 = 2 * err;

        if (e2 > -dy) {
            err -= dy;
            x += sx;
        }

        if (e2 < dx) {
            err += dx;
            y += sy;
        }
    }

    return points;
}

/////////////////////////////////	WZ2100 helper functions (uses the WZ2100 JS API)	/////////////////////////////////

/**
 * Converts an array of structures represented as lightweight "FishBot objects" into actual game objects.
 * This is part of the algorithm to avoid the use of 'enumStruct()' to get up to date game objects. 
 * @param {FbObject[]} fbStructureList 
 * @returns {StructureObject[]} array containing idle `StructureObjects`.
 */
function getIdleStructureObjects(fbStructureList) {
	let idleStructList = [];
	fbStructureList.forEach(structObj => {
		if (!(structObj.flags & OBJ_FLAGS.IS_BUILT)) {
			return;
		}
		const s = getObject(structObj.type, structObj.player, structObj.id);
		if (s == null) {
			return;
		}
		if (structureIdle(s)) {
			idleStructList.push(s);
		}
	});
	return idleStructList;
};

function isAntiAirDefense(obj) {
	if (obj.canHitAir === true && obj.canHitGround === false) {
		if (obj.droidType === DROID_WEAPON || obj.stattype === DEFENSE) {
			return true;
		}
	}
	return false;					
}

function isEnemy(playerID) {
	if (!defined(playerID)) {
		debug("isEnemy(): playerID is undefined. Check the calling function.");
	}
	return !allianceExistsBetween(me, playerID);
}

/**
 * Returns the Coordinate of the one of the initial trucks (or `baseLocation`, if sufficiently close by).
 * Intent: reduces the unnecessary movement of trucks at the start of the game. 
 * Assumes the map spawns the initial trucks somewhere safe near the player's baseLocation.
 * @returns {Coordinate}
 */
function getTruckStartingLocation() {
	const bx = baseLocation.x, by = baseLocation.y;

	/** @type {Coordinate} */
	let startingLocation = [bx, by];
	
	const MAX_SQ_DISTANCE = 5 ** 2;
	
	const initialTrucks = enumDroid(me, DROID_CONSTRUCT);
	for (let i=0; i<initialTrucks.length; i++) {
		const u = initialTrucks[i];
		const truckDistSq = distSq(u.x, bx, u.y, by);
		// debug(`Truck ${i}: ${truckDistSq}`);
		if (truckDistSq > MAX_SQ_DISTANCE) {
			startingLocation[0] = u.x;
			startingLocation[1] = u.y;
			deb(`Using truck location (${u.x}, ${u.y}) as the startLoc.`);
			break;
		}
	}

	return startingLocation;
}

/**
 * Returns the BFS order of the coordinates of all walkable tiles from the player's base location (or the location of one of the initial trucks).
 * @param {(boolean[])[]} isBaseNonReachableTile
 * @returns {Coordinate[]} i.e. array of 'tuples'
 */
function getWalkableTiles(isBaseNonReachableTile) {
	const xMax = mapWidth;
	const yMax = mapHeight;

	/** @type {Coordinate[]} */
	const visited = [];
	const isVisited = new Array(xMax * yMax).fill(false);

	/** @type {Coordinate[]} */
	const toSearch = [getTruckStartingLocation()];
	const inSearchList = new Array(xMax * yMax).fill(false);	

	const MAX_MAP_DIM = 256;
	const MAX_ITERS = Math.min(xMax * yMax, MAX_MAP_DIM * MAX_MAP_DIM);
	let iters = 0;
	
	// Formatted as [x, y, manhattanDistance]
	// const NEIGHBOUR_OFFSETS = [[-1, -1, 2], [-1, 0, 1], [-1, 1, 2], [0, 1, 1], [1, 1, 2], [1, 0, 1], [1, -1, 2], [0, -1, 1]];		// allows for diagonal movement (more optimistic estimate of walkable tiles)
	const NEIGHBOUR_OFFSETS = [[-1, 0, 1], [0, 1, 1], [1, 0, 1], [0, -1, 1]];		// up / down / left / right movement only (more conservative estimate of walkable tiles)

	while (toSearch.length != 0 && iters < MAX_ITERS) {
		const node = toSearch.shift();
		if (node == undefined) {
			break;
		}
		const x = node[0], y = node[1];

		visited.push(node);
		isVisited[y * xMax + x] = true;

		// Check neighbours
		NEIGHBOUR_OFFSETS.forEach(o => {
			const ox = o[0] + node[0];
			const oy = o[1] + node[1];
			const oIdx = oy * xMax + ox;
			// const d = o[2];

			// Check in map bounds
			if (ox < 0 || ox >= xMax)  			return;
			if (oy < 0 || oy >= yMax) 			return;

			// Check if tile is already accounted for
			if (isVisited[oIdx]) 				return;
			if (inSearchList[oIdx]) 			return;

			// Check if walkable
			if (isBaseNonReachableTile[ox][oy]) 	return;

			toSearch.push([ox, oy]);
			inSearchList[oIdx] = true;
		});

		iters++;
	}

	if (false) {
		debug(`Completed BFS in ${iters} iterations (walkable tiles = ${visited.length}).`);
		// visited.forEach(v => debug(`${v[0]}, ${v[1]}`));		// prints out all of the tilecos in question
	}

	return visited;
}
