"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program.
	If not, see <https://www.gnu.org/licenses/>.
"""

"""
The terrain tileset determines how each tile in a WZ2100 map is rendered.
    Dry maps use "ARIZONA", urban maps use "URBAN" and mountainous maps use "ROCKIES".

The local file `addon.lev` is directly copied from:
https://github.com/Warzone2100/warzone2100/blob/master/data/mp/addon.lev

The objective of this file is to extract the tileset information from addon.lev 
    to create a lookup table that the map-repackager can use to determine the map's tileset.

This seems to be how it is implemented inside the Warzone2100 source code, e.g. see

https://github.com/Warzone2100/warzone2100/blob/2c7c3d486a3ebd42b20887cdf3c58bbe0f2e12d1/src/multiint.cpp#L755
`static void loadMapPreview(bool hideInterface, std::string mapName, const Sha256& mapHash)`

which calls:

https://github.com/Warzone2100/warzone2100/blob/2c7c3d486a3ebd42b20887cdf3c58bbe0f2e12d1/src/multiint.cpp#L632
static MAP_TILESET guessMapTilesetType(LEVEL_DATASET *psLevel)

Inside this function, the core lines are:

```
	if (psLevel->psBaseData && !psLevel->psBaseData->pName.empty())
	{
		if (sscanf(psLevel->psBaseData->pName.c_str(), "MULTI_CAM_%u", &c) != 1)
		{
			sscanf(psLevel->psBaseData->pName.c_str(), "MULTI_T%u_C%u", &t, &c);
		}
	}

	switch (c)
	{
	case 1:
		return MAP_TILESET::ARIZONA;
		break;
	case 2:
		return MAP_TILESET::URBAN;
		break;
	case 3:
		return MAP_TILESET::ROCKIES;
		break;
	}
```

Searching for: `MULTI_T` in the source code gives `addon.lev`. `addon.lev` contains the link between:
    'level' (user-facing name), 
    'dataset' (the last number is the tileset) and 
    'game' (the .gam file that I am replacing in my re-packager with level.json and gam.json).
    
Disclaimer: The rest of this file is mostly generated by AI.
"""

from pathlib import Path


def parse_tileset_from_dataset(dataset: str) -> str:
    """
    Convert Warzone dataset name into tileset name.

    Mirrors wz2100 guessMapTilesetType().
    Defaults to arizona if unknown.
    """

    if dataset.startswith("MULTI_CAM_"):
        try:
            c = int(dataset.split("_")[-1])
        except ValueError:
            c = 0

    elif dataset.startswith("MULTI_T"):
        try:
            c = int(dataset.split("_C")[-1])
        except ValueError:
            c = 0

    else:
        c = 0

    if c == 1:
        return "arizona"

    if c == 2:
        return "urban"

    if c == 3:
        return "rockies"

    return "arizona"


def parse_tileset_from_lev(lev_path: Path, map_folder_name: str) -> str:
    """
    Extract tileset from addon.lev using the map folder name.

    map_folder_name example:
        3c-Gamma

    Falls back to arizona if the dataset cannot be determined.
    """

    game_filename = f"{map_folder_name}.gam"

    lines = lev_path.read_text().splitlines()

    for index, line in enumerate(lines):
        line = line.strip()

        if not line.startswith("game"):
            continue

        if game_filename not in line:
            continue

        # Search backwards inside this level definition
        for previous in reversed(lines[:index]):
            previous = previous.strip()

            if previous.startswith("dataset"):
                dataset = previous.split()[1]
                return parse_tileset_from_dataset(dataset)

            if previous.startswith("level"):
                break

    return "arizona"


if __name__ == "__main__":
    tileset = parse_tileset_from_lev(
        Path("addon.lev"),
        "2c-urbanchasm",
    )

    print(tileset)
