"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program. 
	If not, see <https://www.gnu.org/licenses/>.
"""

# The purpose of this file is to make merge commits easier.
# Disclaimer: Mostly generated by AI.

# Specify the path to your local Git repository
from git import Repo
import os

# Specify the path to your local Git repository
# '.' refers to the current directory
repo_path = rf'C:\Users\%USERNAME%\OneDrive\Documents\wz2100_config_dir\mods\4.6.3\autoload\fishbot' 
repo = Repo(repo_path)


############ USER CONFIG #############
repo.heads['v0.3.2-development'].checkout()

# Define your hashes
start_hash  = "0565344"
end_hash = "200c86b"

############ END CONFIG #############

# Get all commits in the range
commits = list(repo.iter_commits(f"{start_hash}..{end_hash}"))

for commit in commits:
    print(f"\n{commit.message.strip()}")
    
print("GitHub diff:")
print(f"https://github.com/fishbotdev/fishbot/compare/{start_hash}...{end_hash}")


# # Iterate over all commits
# commits = repo.iter_commits()

# for commit in commits:
#     print(f"Commit SHA: {commit.hexsha}")
#     print(f"Author: {commit.author.name}")
#     print(f"Date: {commit.committed_datetime}")
#     print(f"Message: {commit.message.strip()}")
#     print("-" * 40)