"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program.
	If not, see <https://www.gnu.org/licenses/>.
"""

# The purpose of this script is to create challenge json files e.g.
# a custom challenge .json file (see `warzone2100/data/mp/tests/miza.json` for example)

# These files should be placed in your `wz2100_config_directory/tests` folder to be read successfully by the game.

# Disclaimer: This file is mostly generated by AI.


"""
Example output `.json`:

{
	"challenge": {
		"bases": 1,
		"map": "Gamma",
		"powerLevel": 2,
		"scavengers": "false",
		"techLevel": 2
	},
	"player_0": {
	    "team": 1,
	},
	"player_1": {
		"difficulty": "Medium",
		"team": 1,
		"ai": "fishbot/multiplay/skirmish/FishBot.js"
	},
	"player_2": {
		"difficulty": "Insane",
		"team": 0,
		"ai": "multiplay/skirmish/Cobra.js"
	}
}

"""

import json

FISHBOT_AI = "fishbot/multiplay/skirmish/FishBot.js"
COBRA_AI = "multiplay/skirmish/Cobra.js"
SPECTATOR_AI = "Spectator.js"

EASY_DIFFICULTY = "Easy"
MEDIUM_DIFFICULTY = "Medium"
HARD_DIFFICULTY = "Hard"
INSANE_DIFFICULTY = "Insane"

#################################### HELPER FUNCTIONS ####################################

def create_empty_player(team=1):
    return {
        "team": team,
        "ai": SPECTATOR_AI
    }


def create_fishbot_player(team=1, difficulty=MEDIUM_DIFFICULTY):
    return {
        "difficulty": difficulty,
        "team": team,
        "ai": FISHBOT_AI
    }


def create_cobra_player(team=0, difficulty=INSANE_DIFFICULTY):
    return {
        "difficulty": difficulty,
        "team": team,
        "ai": COBRA_AI
    }


def generate_challenge(map_name="Gamma",
                       bases=1, power_level=2, scavengers=False, tech_level=2,
                       total_players=8, fishbot_position: int=1, cobra_position: int=2):
    data = {
        "challenge": {
            "bases": bases,
            "map": map_name,
            "powerLevel": power_level,
            "scavengers": str(scavengers).lower(),
            "techLevel": tech_level
        }
    }

    # Fill all slots with empty players
    for i in range(total_players):
        data[f"player_{i}"] = create_empty_player()

    # Insert FishBot
    data[f"player_{fishbot_position}"] = create_fishbot_player(
        team=1,
        difficulty=MEDIUM_DIFFICULTY
    )

    # Insert Cobra
    data[f"player_{cobra_position}"] = create_cobra_player(
        team=0,
        difficulty=HARD_DIFFICULTY
    )

    return data


def save_challenge_file(filename, data):

    with open(filename, "w") as f:
        json.dump(data, f, indent=4)

    print(f"Generated: {filename}")


#################################### MAIN ####################################

if __name__ == "__main__":

    MAP_INFO = [
        {
            "name": "Entropy",
            "maxPlayers": 6,
            "fishbot_position": 1,
            "cobra_position": 5
        },
        {
            "name": "Melting",
            "maxPlayers": 6,
            "fishbot_position": 4,
            "cobra_position": 1
        }
    ]

    for m in MAP_INFO:
        NAME: str = m['name']
        MAX_PLAYERS = m['maxPlayers']
        FISHBOT_POSITION = m['fishbot_position']
        COBRA_POSITION = m['cobra_position']

        FILE_NAME = f"{NAME.upper()}.json"

        data = generate_challenge(map_name=NAME, total_players=MAX_PLAYERS,
                                  fishbot_position=FISHBOT_POSITION, cobra_position=COBRA_POSITION)

        save_challenge_file(FILE_NAME, data)

