"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program.
	If not, see <https://www.gnu.org/licenses/>.
"""

# The purpose of this script is to create challenge json files e.g. a custom challenge .json file 
# (see `warzone2100/data/mp/tests/miza.json` or `warzone2100/data/mp/challenges/hidebehind.json` for example).
# These files should be placed in your `wz2100_config_directory/tests` folder to be read successfully by the game.

# Disclaimer: This file is mostly generated by AI.


"""
Example output `.json`:
Note: This code defines what the fields under "challenge" look like: https://github.com/Warzone2100/warzone2100/blob/8701c62ae68ca70da43ec915cbf6776c492e6656/src/multiint.cpp#L4848.

{
	"challenge": {
		"bases": 1,
		"map": "Gamma",
		"powerLevel": 2,
		"scavengers": "false",
		"techLevel": 2
	},
	"player_0": {
	    "team": 1,
	},
	"player_1": {
		"difficulty": "Medium",
		"team": 1,
		"ai": "fishbot/multiplay/skirmish/FishBot.js"
	},
	"player_2": {
		"difficulty": "Insane",
		"team": 0,
		"ai": "multiplay/skirmish/Cobra.js"
	}
}

"""

import json

FISHBOT_AI = "fishbot/multiplay/skirmish/FishBot.js"
COBRA_AI = "Cobra.js"
SPECTATOR_AI = "Spectator.js"       # this is a custom spectator AI script with details below

"""

`Spectator.js` contains:
---
function eventStartLevel() {
	transformPlayerToSpectator(me);	
}
---
while `Spectator.json` contains:
---
{
	"AI": {
		"js": "Spectator.js",
		"name": "Spectator",
		"tip": "Sets itself to a spectator as soon as the game starts."
	}
}
---
"""


EASY_DIFFICULTY = "Easy"
MEDIUM_DIFFICULTY = "Medium"
HARD_DIFFICULTY = "Hard"
INSANE_DIFFICULTY = "Insane"

#################################### HELPER FUNCTIONS ####################################

def get_uppercase_ai_name(script_name):
    # Turns `Cobra.js` -> `COBRA`
    return (script_name.split(".")[0]).upper()

def create_empty_player(team=1):
    return {
        "difficulty": EASY_DIFFICULTY,
        "team": team,
        "ai": SPECTATOR_AI,
    }


def create_fishbot_player(team=1, difficulty=MEDIUM_DIFFICULTY):
    return {
        "difficulty": difficulty,
        "team": team,
        "ai": FISHBOT_AI
    }


def create_cobra_player(team=0, difficulty=INSANE_DIFFICULTY):
    return {
        "difficulty": difficulty,
        "team": team,
        "ai": COBRA_AI
    }


def generate_1v1_challenge(challenge_name, challenge_version, map_name, total_players,
                           bases, power_level, scavengers, tech_level,
                           fishbot_position, fishbot_difficulty, fishbot_factory,
                           opponent_position, opponent_difficulty, opponent_factory):
    data = {
        "challenge": {
            "bases": bases,
            "map": map_name,
            "powerLevel": power_level,
            "scavengers": scavengers,
            "techLevel": tech_level,

            "name": challenge_name,
            "version": challenge_version
        }
    }

    # The "OPPONENT TEAM" should only contain the opponent player(s).
    # In a 1v1 - this means that the opponent will not activate any 'team-related' code, which may put it at a disadvantage.
    # e.g. Cobra begins using artillery only.
    OPPONENT_TEAM = 0
    FISHBOT_TEAM = 1        # this team should contain FishBot & all spectator players.

    # Fill all slots with empty players
    for i in range(total_players):
        data[f"player_{i}"] = create_empty_player(team=FISHBOT_TEAM)

    # Insert FishBot
    data[f"player_{fishbot_position}"] = fishbot_factory(
        team=FISHBOT_TEAM,
        difficulty=fishbot_difficulty
    )

    # Insert Cobra
    data[f"player_{opponent_position}"] = opponent_factory(
        team=OPPONENT_TEAM,
        difficulty=opponent_difficulty
    )

    return data


def save_challenge_file(filename, data):

    with open(filename, "w") as f:
        json.dump(data, f, indent=4)

    print(f"Generated: {filename}")


###############################################################################################

if __name__ == "__main__":

    #################################### USER CONFIG START ####################################

    SKIRMISH_1V1_INFO = {
        # Challenge settings
        "version": 1,

        # Fishbot info
        "fishbotName": FISHBOT_AI,
        "fishbotDifficulty": MEDIUM_DIFFICULTY,
        "fishbotFactory": create_fishbot_player,

        # Opponent info
        "opponentName": COBRA_AI,
        "opponentDifficulty": HARD_DIFFICULTY,
        "opponentFactory": create_cobra_player,

        # Game settings
        "bases": 1,
        "powerLevel": 2,
        "scavengers": 0,
        "techLevel": 2,
    }


    MAP_INFO_COBRA_1V1 = [

        # 2p maps (note: these are not included because challenge maps force add a human player as Player 0).

        # 3p maps 
        {
            "mapName": "Monocot",
            "maxPlayers": 3,
            "fishbot_position": 1,
            "opponent_position": 2
        },
        {
            "mapName": "Gamma",
            "maxPlayers": 3,
            "fishbot_position": 1,
            "opponent_position": 2
        },

        # # 6p maps
        # {
        #     "name": "Entropy",
        #     "maxPlayers": 6,
        #     "fishbot_position": 1,
        #     "opponent_position": 5
        # },
        # {
        #     "name": "Melting",
        #     "maxPlayers": 6,
        #     "fishbot_position": 4,
        #     "opponent_position": 1
        # }
    ]

    #################################### USER CONFIG END ####################################


    # BOT INFO
    FISHBOT_DIFFICULTY = SKIRMISH_1V1_INFO['fishbotDifficulty']
    fishbot_factory = SKIRMISH_1V1_INFO['fishbotFactory']
    OPPONENT_NAME = get_uppercase_ai_name(SKIRMISH_1V1_INFO['opponentName'])
    OPPONENT_DIFFICULTY = SKIRMISH_1V1_INFO['opponentDifficulty']
    opponent_factory = SKIRMISH_1V1_INFO['opponentFactory']

    # SKIRMISH INFO
    BASES = SKIRMISH_1V1_INFO['bases']
    POWER_LEVEL = SKIRMISH_1V1_INFO['powerLevel']
    SCAVENGERS = SKIRMISH_1V1_INFO['scavengers']
    TECH_LEVEL = SKIRMISH_1V1_INFO['techLevel']


    for m in MAP_INFO_COBRA_1V1:
        # MAP INFO
        MAP_NAME: str = m['mapName']
        MAX_PLAYERS = m['maxPlayers']
        POSITION1 = m['fishbot_position']
        POSITION2 = m['opponent_position']

        POSITIONS = [POSITION1, POSITION2]
        NUM_POSITIONS = len(POSITIONS)

        # Creates two copies with positions swapped
        for i in range(NUM_POSITIONS):

            FISHBOT_POSITION = POSITIONS[i % NUM_POSITIONS]
            OPPONENT_POSITION = POSITIONS[(i+1) % NUM_POSITIONS]

            FILE_NAME = f"{MAP_NAME.upper()}_{FISHBOT_POSITION}_{OPPONENT_POSITION}_{OPPONENT_NAME}_{OPPONENT_DIFFICULTY.upper()}_T{TECH_LEVEL}.json"
            FILE_VER = 1

            data = generate_1v1_challenge(
                # Map & game setup
                challenge_name=FILE_NAME, challenge_version=FILE_VER, map_name=MAP_NAME, total_players=MAX_PLAYERS,
                bases=BASES, power_level=POWER_LEVEL, scavengers=SCAVENGERS, tech_level=TECH_LEVEL,
                # Player setup
                fishbot_position=FISHBOT_POSITION, fishbot_difficulty=FISHBOT_DIFFICULTY, fishbot_factory=fishbot_factory,
                opponent_position=OPPONENT_POSITION, opponent_difficulty=OPPONENT_DIFFICULTY, opponent_factory=opponent_factory,
            )

            save_challenge_file(FILE_NAME, data)
