"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program.
	If not, see <https://www.gnu.org/licenses/>.
"""

# The purpose of this script is to demonstrate a method (Python 3.11 on Windows 11) which can be used to:
# 1. automatically run a WZ2100 bot vs bot game
# 2. save the result internally within Python for further processing

"""
~ Historical Context ~

At the start of the project I found that:

`   "Warzone 2100\bin\warzone2100.exe" --configdir="Warzone 2100\PRODCONFIG" --skirmish="GAMMA_HARD_COBRA_T2.json" --enableconsole --headless --autogame     `

ran allowed me to run autogames in a Windows console directly. The console output could then be saved using the "Export text" button in the Windows 11 command prompt.

Initially I tried:
- subprocess.run(... capture_output=True, text=True) 
- subprocess.run(... stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True) 
- subprocess.Popen(... stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
- winpty .spawn() (emulating a terminal internally)
and no dice. It seems like WZ2100 does not write to stdout/stderr by default using my existing `--autogame` command above.

Then I tried various combinations of these command line flags:
1. "--debugfile=blah.log"      
2. "--debug=all"                   ***
3. "--flush-debug-stderr"
but although I was able to obtain out the raw (internal) debug output in `blah.log` (when using 1. and 2. together), this did not contain the summary results table printed to the console with `--autogame`.

*** Note: to find the <flags> for the `debug=<flags>` command line argument:
1. `clparse.cpp` defines the command line functions.
2. Check --debug flag -> https://github.com/Warzone2100/warzone2100/blob/8701c62ae68ca70da43ec915cbf6776c492e6656/src/clparse.cpp#L530
3. Usage is --debug=<flag>. So what are the acceptable values of 'flag'?
4. Check function `debug_enable_switch` -> https://github.com/Warzone2100/warzone2100/blob/master/lib/framework/debug.cpp#L434
5. Then `code_part_from_str` -> https://github.com/Warzone2100/warzone2100/blob/master/lib/framework/debug.cpp#L140
6. Then `code_part_names` -> https://github.com/Warzone2100/warzone2100/blob/master/lib/framework/debug.cpp#L87C20-L127
and these are the necessary flags for 'debug=<flags>'.

Finally, I tried scraping the IDE console after subprocess.run() finished executing, which did finally work.

Disclaimer: most of the helper functions are generated by AI, with a few manual modifications for readability.
"""

import subprocess
import os

from typing import List
import ctypes

import pandas as pd
import json

from time import perf_counter


#################################### HELPER FUNCTIONS ####################################

def clear_console():
    # Use 'cls' for Windows (os.name == 'nt') and 'clear' for Linux/macOS
    os.system('cls' if os.name == 'nt' else 'clear')

"""
Usage notes (`windows_scrape_terminal_history`):
    - Tested working on Win11 OS; Linux/Mac will need a different implementation for compatibility
    - If using a PyCharm IDE (e.g. 2026.1.2) you will need to enable the "Emulate Terminal In Output Console" option in
      the "Edit Configuration" / "Run Configuration" panel get the output of --autogame to print to the console.
      VSCode appears to show the terminal output by default so no special actions may be required.
"""
def windows_scrape_terminal_history(lines_to_read):
    """
    Extracts printed text directly from the current Windows 
    console host window's screen buffer matrix.
    """
    kernel32 = ctypes.windll.kernel32
    # -11 references the standard active output device handle
    stdout_handle = kernel32.GetStdHandle(-11) 
    
    class COORD(ctypes.Structure):
        _fields_ = [("X", ctypes.c_short), ("Y", ctypes.c_short)]
        
    class SMALL_RECT(ctypes.Structure):
        _fields_ = [("Left", ctypes.c_short), ("Top", ctypes.c_short), 
                    ("Right", ctypes.c_short), ("Bottom", ctypes.c_short)]
                    
    class CONSOLE_SCREEN_BUFFER_INFO(ctypes.Structure):
        _fields_ = [("dwSize", COORD), ("dwCursorPosition", COORD),
                    ("wAttributes", ctypes.c_ushort), ("srWindow", SMALL_RECT),
                    ("dwMaximumWindowSize", COORD)]
        
    csbi = CONSOLE_SCREEN_BUFFER_INFO()
    kernel32.GetConsoleScreenBufferInfo(stdout_handle, ctypes.byref(csbi))
    
    # Calculate the bounding block to extract from based on where the cursor left off
    start_row = max(0, csbi.dwCursorPosition.Y - lines_to_read)
    read_coord = COORD(0, start_row)
    total_cells = csbi.dwSize.X * lines_to_read
    
    chars_read = ctypes.c_ulong(0)
    buffer_allocation = ctypes.create_string_buffer(total_cells)
    
    # Scrape the raw Win32 console cell text grid
    kernel32.ReadConsoleOutputCharacterA(
        stdout_handle, buffer_allocation, total_cells, read_coord, ctypes.byref(chars_read)
    )
    
    raw_text = buffer_allocation.value.decode('utf-8', errors='ignore')
    
    # Slice the continuous buffer string back into clean, individual console lines
    formatted_lines = []
    for i in range(0, len(raw_text), csbi.dwSize.X):
        line_chunk = raw_text[i:i + csbi.dwSize.X].rstrip()
        if line_chunk:  # Skip empty whitespace lines
            formatted_lines.append(line_chunk)
            
    return formatted_lines


# Inherits input parameter descriptions from the inbuilt Python `range()` function.
def generate_range(start: int, stop: int, step: int) -> List[int]:
    return list(range(start, stop, step))


def find_final_game_summary_table_index(console_history: List[str]) -> int:
    GAME_SUMMARY_TABLE_TITLE = "Game State"
    GAME_SUMMARY_TABLE_IDX = 0    # if GAME_STATE_TABLE_TEXT not found, returns the whole history

    LIST_LENGTH = len(console_history)
    REVERSED_LIST_INDEXES = generate_range(start=LIST_LENGTH-1, stop=-1, step=-1)

    for i in REVERSED_LIST_INDEXES:
        if GAME_SUMMARY_TABLE_TITLE in console_history[i]:
            GAME_SUMMARY_TABLE_IDX = i
            break
    else:
        print(f'WARNING: could not find string: "{GAME_SUMMARY_TABLE_TITLE}"')
    
    return GAME_SUMMARY_TABLE_IDX


def print_game_summary(game_summary_table: List[str]) -> None:
    print("\n\n--- Final Game Summary ---\n\n")
    for line in game_summary_table:
        print(line)


"""
Usage notes (`extract_stats_from_summary_table`):
This script ignores the 'Player' that is force-added to challenge maps.
"""
def extract_stats_from_summary_table(summary_table: List[str]) -> pd.DataFrame:
    """
    Extract player summary rows from game output.

    Expected dataframe columns:
        player_id      int
        name           str
        extract_power  int
        units_killed   int
        structures     int
        factories      int
        research       int
        units_alive    int
        power          int
        defeated       bool
    """

    rows = []

    for line in summary_table:
        if "|" not in line:
            continue

        parts = [p.strip() for p in line.split("|")]

        # Skip malformed rows
        if len(parts) < 7:
            continue

        # Skip table headers
        if parts[0] in {"#", "--"}:
            continue

        try:
            player_id = int(parts[0])
            name = parts[1]

            # Ignore observer/player row
            if name.lower() == "player":
                continue

            extract_power = int(parts[2])
            units_killed = int(parts[3])

            # Example: "51 (5/4)"
            struct_text = parts[4]

            structures_part, sub_part = struct_text.split("(")

            structures = int(structures_part.strip())

            sub_part = sub_part.replace(")", "")
            factories, research = map(int, sub_part.split("/"))

            units_alive = int(parts[5])
            power = int(parts[6])

            defeated = (
                len(parts) > 7 and parts[7].lower() == "x"
            )

            rows.append({
                "player_id": player_id,
                "name": name,
                "extract_power": extract_power,
                "units_killed": units_killed,
                "structures": structures,
                "factories": factories,
                "research": research,
                "units_alive": units_alive,
                "power": power,
                "defeated": defeated,
            })

        except (ValueError, IndexError):
            continue

    return pd.DataFrame(rows)


def append_match(df: pd.DataFrame, path: str) -> None:
    records = df.to_dict(orient="records")

    with open(path, "a") as f:
        for record in records:
            f.write(json.dumps(record) + "\n")

        f.flush()
        os.fsync(f.fileno())

#################################### TEST RUNNERS ####################################

def run_autogame(commands: List[str]) -> List[str]:
    # Execute normally (let WZ write directly to the console)
    subprocess.run(commands)        # blocking (only returns once the process is finished)
    del commands

    # Scrapes the console output and stores it into `console_history`, then clears the console in prep for further processing
    console_history = windows_scrape_terminal_history(lines_to_read=1000)

    # Gets the final game summary table
    summary_table_start_idx = find_final_game_summary_table_index(console_history)
    final_game_summary_table = console_history[summary_table_start_idx:]
    del summary_table_start_idx

    return final_game_summary_table


#################################### MAIN ####################################

if __name__ == "__main__":
    """
    The intended data pipeline is:
    1. Run autogame
    2. Scrape console + store into dataframe
    3. Convert dataframe + test metadata to jsonl (storing the intermediate result for data safety in case of interruptions)
    The `results.jsonl` file will be processed back into a dataframe by the processing script.
    
    The jsonl pipeline is picked because its a good compromise between code complexity, speed & human-readability.
    Extra memory usage (compared to .log/.txt writing) is not an issue for this application.

    The other options I considered were:
     1. Writing to .log/.txt (although faster) requires a custom parser & the performance improvement is minimal 
     for this application (the tests can take up to ~1min each; saving 0.5 seconds at best doesn't make a material difference).
     2. Writing to Excel (as .xlsx or .csv) adds unnecessary overhead to configure the file properly.
    """

    clear_console()

    # Note: The `windows_scrape_terminal_history` function is the core technical component of this script.
    # This function is platform (OS) & IDE dependent - please see the usage notes above this function.

    ######## PROGRAM CONFIGURATION ########

    CHALLENGE_JSON_NAME = "GAMMA_INSANE_COBRA_T2"
    NUM_TESTS = 50
    DEBUG_ON = False

    COMMIT_SHA = """
    c6bf1b52487f27cba5a40d89b7e8553759f47322
    """

    # Reminder: remove any previous .jsonl files if necessary

    ######## END PROGRAM CONFIGURATION ########

    SHORT_SHA = COMMIT_SHA.lstrip()[:7]
    OUTPUT_FILE_NAME = f"{SHORT_SHA},{CHALLENGE_JSON_NAME},{NUM_TESTS}G.jsonl"

    """
    Note: I cloned FishBot into a new configuration directory ('PRODCONFIG') and am running autogames from 
        this 'production' folder (this explains the file paths for `warzone2100.exe` & `PRODCONFIG`).
    This means I can run autogames & perform development simultaneously using the same `warzone2100.exe`, e.g. 
    1. different config directories for dev / prod => (allows for) 
    2. different mods directories => 
    3. different FishBot instances
    
    PRODCONFIG is a clone of the devconfig folder. This means that changes to the development config directory
        (e.g. a new `challenge.json` from the 'tests' folder) can be pulled from version control.
        
    The development / production environment split is not strictly necessary but it has made development + testing
        a lot more streamlined!
    """

    # Check the parent folder: `fishbot` is set as the current working directory.

    AUTOGAME_COMMAND = [
        rf"Warzone 2100\bin\warzone2100.exe",           # assumes WZ2100 is installed in the current working directory
        rf'--configdir="Warzone 2100\PRODCONFIG"',      # assumes that the mod is loaded in a "PRODCONFIG" subfolder of the WZ2100 install
        rf'--skirmish="{CHALLENGE_JSON_NAME}.json"',    # a custom challenge .json file loaded into `configdir/tests` (see `warzone2100/data/mp/tests/miza.json` for an example). The test file must be added to the 'tests' folder: https://github.com/Warzone2100/warzone2100/blob/8701c62ae68ca70da43ec915cbf6776c492e6656/src/multiint.cpp#L526
        rf"--enableconsole",                            # creates a console (this is where the Game State summary is printed)
        rf"--headless",                                 # runs the program without a GUI
        rf"--autogame"                                  # automatically runs the game
    ]

    # Run the test
    TIME_STARTED = perf_counter()
    print_iteration = lambda i: print(f"\n\n Iteration {i + 1} \n\n")

    for i in range(NUM_TESTS):
        clear_console()
        print_iteration(i)

        final_summary_table = run_autogame(AUTOGAME_COMMAND)

        if DEBUG_ON:
            clear_console()
            print_iteration(i)
            print_game_summary(final_summary_table)
            ADD_DEBUG_BREAKPOINT_HERE_TO_SEE_THE_EXTRACTED_RESULTS_TABLE = 1

        stats = extract_stats_from_summary_table(final_summary_table)
        stats["match_id"] = i   # Record test metadata for batch processing later

        ADD_DEBUG_BREAKPOINT_HERE_TO_SEE_STATS_AS_DATAFRAME = 1

        append_match(df=stats, path=OUTPUT_FILE_NAME)


    TIME_ENDED = perf_counter()
    round_to_2dp = lambda x: round(x, 2)

    clear_console()
    SECS_TO_COMPLETE = round_to_2dp(TIME_ENDED - TIME_STARTED)
    MINS_TO_COMPLETE = round_to_2dp(SECS_TO_COMPLETE / 60.0)
    print(f"\nScript finished {NUM_TESTS} tests in {SECS_TO_COMPLETE} seconds ({MINS_TO_COMPLETE} minutes)")
