"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program. 
	If not, see <https://www.gnu.org/licenses/>.
"""

# Disclaimer: This script is generated by AI.

from collections import Counter
import matplotlib.pyplot as plt

timeslots = [1,1,2,3,4,4,6,8,9,10,11,12,13,14,16,18,18,19,21,22,23,24,25,26,26,28,29,31,32,33,34,34,36,38,38,39,40,41,42,43,44,46,48,49,51,51,52,53,54,55,56,58,58,59,61,62,63,64,64,66,68,69,70,71,72,73,74,76,76,78,78,79,81,82,83,84,85,86,87,88,89,91,92,93,94,94,96,98,98,99,100,101,101,102,103,104,106,108,109,111,112,113,114,115,116,118,118,119,121,122,123,124,124,126,126,128,129,130,131,132,133,134,136,138,138,139,141,142,143,144,145,146,148,149,151,151,152,153,154,154,156,158,158,159,160,161,162,163,164,166,168,169,171,172,173,174,175,176,176,178,178,179,181,182,183,184,184,186,188,189,190,191,192,193,194,196,198,198,199,201,201,202,203,204,205,206,208,209,211,212,213,214,214,216,218,218,219,220,221,222,223,224,226,226,228,229,231,232,233,234,235,236,237,238,238,239,241,242,243,244,244,246,248,249,250,251,251,252,253,254,256,258,258,259,261,262,263,264,265,266,268,269,271,272,273,274,274,276,276,278,278,279,280,281,282,283,284,286,288,289,291,292,293,294,295,296,298,298,299]

TOTAL_SLOTS = len(timeslots)

# Count tasks per slot
slot_counts = Counter(timeslots)

# Fill missing slots with 0
tasks_per_slot = [slot_counts.get(i, 0) for i in range(TOTAL_SLOTS)]

# Frequency table (frames with N tasks)
load_frequency = Counter(tasks_per_slot)

print("Frames per task count:")
for tasks, frames in sorted(load_frequency.items()):
    print(f"{frames} = {tasks} task")


# plots side-by-side:
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.hist(timeslots, bins=range(TOTAL_SLOTS+1))
plt.title("Timeslot Distribution")

plt.subplot(1,2,2)
plt.hist(tasks_per_slot, bins=range(max(tasks_per_slot)+2))
plt.title("Tasks Per Frame")

plt.show()