"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program. 
	If not, see <https://www.gnu.org/licenses/>.
"""

# Disclaimer: This script is generated by AI.

from collections import Counter
import matplotlib.pyplot as plt

timeslots = [1,2,3,4,5,6,8,8,9,11,11,13,14,16,17,18,19,21,23,24,25,26,28,29,31,32,33,33,34,36,38,39,41,41,43,44,45,46,47,48,49,51,53,54,56,58,58,59,61,62,63,64,65,66,68,69,71,71,73,74,76,77,78,79,81,83,83,84,85,86,88,89,91,92,93,94,94,96,98,99,101,101,103,104,105,106,107,108,108,109,111,113,114,116,118,119,121,122,123,124,125,126,128,129,131,131,133,133,134,136,137,138,139,141,143,144,145,146,148,149,151,152,153,154,156,158,158,159,161,161,163,164,165,166,167,168,169,171,173,174,176,178,179,181,182,183,183,184,185,186,188,189,191,191,193,194,196,197,198,199,201,203,204,205,206,208,208,209,211,212,213,214,216,218,219,221,221,223,224,225,226,227,228,229,231,233,233,234,236,238,239,241,242,243,244,244,245,246,248,249,251,251,253,254,256,257,258,258,259,261,263,264,265,266,268,269,271,272,273,274,276,278,279,281,281,283,283,284,285,286,287,288,289,291,293,294,296,298,299]

TOTAL_SLOTS = len(timeslots)

# Count tasks per slot
slot_counts = Counter(timeslots)

# Fill missing slots with 0
tasks_per_slot = [slot_counts.get(i, 0) for i in range(TOTAL_SLOTS)]

# Frequency table (frames with N tasks)
load_frequency = Counter(tasks_per_slot)

print("Frames per task count:")
for tasks, frames in sorted(load_frequency.items()):
    print(f"{frames} = {tasks} task")


# plots side-by-side:
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.hist(timeslots, bins=range(TOTAL_SLOTS+1))
plt.title("Timeslot Distribution")

plt.subplot(1,2,2)
plt.hist(tasks_per_slot, bins=range(max(tasks_per_slot)+2))
plt.title("Tasks Per Frame")

plt.show()