"""
	This file is part of FishBot, a Warzone 2100 AI.

	FishBot is free software; you can redistribute it and/or modify
	it under the terms of the GNU General Public License as published by
	the Free Software Foundation; either version 2 of the License, or
	(at your option) any later version.

	FishBot is distributed in the hope that it will be useful,
	but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along with this program. 
	If not, see <https://www.gnu.org/licenses/>.
"""

# Disclaimer: this file was generated by AI (Gemini).

import os

def create_folders_at_path(destination_path, new_folder_name):
    # Combine the base path with your new folder name
    full_path = os.path.join(destination_path, new_folder_name)
    subfolders = ["music", "slides", "vids"]
    
    try:
        # Create the main folder (and any missing parent directories)
        os.makedirs(full_path, exist_ok=True)
        
        # Create the 3 subfolders
        for sub in subfolders:
            os.makedirs(os.path.join(full_path, sub), exist_ok=True)
            
        print(f"Success! Folders created at: {os.path.abspath(full_path)}")
    except Exception as e:
        print(f"Failed to create folders: {e}")

# --- USER INPUTS ---
# Use 'r' before the string to handle backslashes correctly on Windows
target_directory = os.path.expandvars(rf"C:\Users\%USERNAME%\Videos")
folder_name = rf"v0.4.0-showc-med-vs-insane"

create_folders_at_path(target_directory, folder_name)
